var shadow$provide = {};
(function(){
'use strict';var f;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
function t(a){var b=typeof a;return b!="object"?b:a?Array.isArray(a)?"array":b:"null"}var aa="closure_uid_"+(Math.random()*1E9>>>0),ba=0;function da(a){const b=[];let c=0;for(const d in a)b[c++]=d;return b};function ea(a,b){a!=null&&this.append.apply(this,arguments)}f=ea.prototype;f.Ba="";f.set=function(a){this.Ba=""+a};f.append=function(a,b,c){this.Ba+=String(a);if(b!=null)for(let d=1;d<arguments.length;d++)this.Ba+=arguments[d];return this};f.clear=function(){this.Ba=""};f.toString=function(){return this.Ba};var u={},fa=null;function v(a){return a!=null&&a!==!1}function ha(a){return a instanceof Array}function w(a,b){return a[t(b==null?null:b)]?!0:a._?!0:!1}function y(a,b){var c=b==null?null:b.constructor;return Error(["No protocol method ",a," defined for type ",v(v(c)?c.Kb:c)?c.pb:t(b),": ",b].join(""))}function ia(a){var b=a.pb;return v(b)?b:z.g(a)}var ja=typeof Symbol!=="undefined"&&t(Symbol)==="function"?Symbol.iterator:"@@iterator";
function C(a){for(var b=a.length,c=Array(b),d=0;;)if(d<b)c[d]=a[d],d+=1;else break;return c}function ka(){}function la(a){if(a!=null&&a.V!=null)a=a.V(a);else{var b=la[t(a==null?null:a)];if(b!=null)a=b.g?b.g(a):b.call(null,a);else if(b=la._,b!=null)a=b.g?b.g(a):b.call(null,a);else throw y("ICounted.-count",a);}return a}function ma(){}
function na(a){if(a!=null&&a.W!=null)a=a.W(a);else{var b=na[t(a==null?null:a)];if(b!=null)a=b.g?b.g(a):b.call(null,a);else if(b=na._,b!=null)a=b.g?b.g(a):b.call(null,a);else throw y("IEmptyableCollection.-empty",a);}return a}function oa(a,b){if(a!=null&&a.U!=null)a=a.U(a,b);else{var c=oa[t(a==null?null:a)];if(c!=null)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=oa._,c!=null)a=c.h?c.h(a,b):c.call(null,a,b);else throw y("ICollection.-conj",a);}return a}function pa(){}
var qa=function(){function a(d,e,g){var h=D[t(d==null?null:d)];if(h!=null)return h.m?h.m(d,e,g):h.call(null,d,e,g);h=D._;if(h!=null)return h.m?h.m(d,e,g):h.call(null,d,e,g);throw y("IIndexed.-nth",d);}function b(d,e){var g=D[t(d==null?null:d)];if(g!=null)return g.h?g.h(d,e):g.call(null,d,e);g=D._;if(g!=null)return g.h?g.h(d,e):g.call(null,d,e);throw y("IIndexed.-nth",d);}var c=null;c=function(d,e,g){switch(arguments.length){case 2:return b.call(this,d,e);case 3:return a.call(this,d,e,g)}throw Error("Invalid arity: "+
arguments.length);};c.h=b;c.m=a;return c}(),D=function D(a){switch(arguments.length){case 2:return D.h(arguments[0],arguments[1]);case 3:return D.m(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length)].join(""));}};D.h=function(a,b){return a!=null&&a.X!=null?a.X(a,b):qa(a,b)};D.m=function(a,b,c){return a!=null&&a.la!=null?a.la(a,b,c):qa(a,b,c)};D.ga=3;
function E(a){if(a!=null&&a.aa!=null)a=a.aa(a);else{var b=E[t(a==null?null:a)];if(b!=null)a=b.g?b.g(a):b.call(null,a);else if(b=E._,b!=null)a=b.g?b.g(a):b.call(null,a);else throw y("ISeq.-first",a);}return a}function G(a){if(a!=null&&a.fa!=null)a=a.fa(a);else{var b=G[t(a==null?null:a)];if(b!=null)a=b.g?b.g(a):b.call(null,a);else if(b=G._,b!=null)a=b.g?b.g(a):b.call(null,a);else throw y("ISeq.-rest",a);}return a}function ra(){}
function sa(a){if(a!=null&&a.S!=null)a=a.S(a);else{var b=sa[t(a==null?null:a)];if(b!=null)a=b.g?b.g(a):b.call(null,a);else if(b=sa._,b!=null)a=b.g?b.g(a):b.call(null,a);else throw y("INext.-next",a);}return a}function ta(){}
var wa=function(){function a(d,e,g){var h=ua[t(d==null?null:d)];if(h!=null)return h.m?h.m(d,e,g):h.call(null,d,e,g);h=ua._;if(h!=null)return h.m?h.m(d,e,g):h.call(null,d,e,g);throw y("ILookup.-lookup",d);}function b(d,e){var g=ua[t(d==null?null:d)];if(g!=null)return g.h?g.h(d,e):g.call(null,d,e);g=ua._;if(g!=null)return g.h?g.h(d,e):g.call(null,d,e);throw y("ILookup.-lookup",d);}var c=null;c=function(d,e,g){switch(arguments.length){case 2:return b.call(this,d,e);case 3:return a.call(this,d,e,g)}throw Error("Invalid arity: "+
arguments.length);};c.h=b;c.m=a;return c}(),ua=function ua(a){switch(arguments.length){case 2:return ua.h(arguments[0],arguments[1]);case 3:return ua.m(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length)].join(""));}};ua.h=function(a,b){return a!=null&&a.ka!=null?a.ka(a,b):wa(a,b)};ua.m=function(a,b,c){return a!=null&&a.H!=null?a.H(a,b,c):wa(a,b,c)};ua.ga=3;function xa(){}
function ya(a,b){if(a!=null&&a.Ua!=null)a=a.Ua(a,b);else{var c=ya[t(a==null?null:a)];if(c!=null)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=ya._,c!=null)a=c.h?c.h(a,b):c.call(null,a,b);else throw y("IAssociative.-contains-key?",a);}return a}function za(a,b,c){if(a!=null&&a.xa!=null)a=a.xa(a,b,c);else{var d=za[t(a==null?null:a)];if(d!=null)a=d.m?d.m(a,b,c):d.call(null,a,b,c);else if(d=za._,d!=null)a=d.m?d.m(a,b,c):d.call(null,a,b,c);else throw y("IAssociative.-assoc",a);}return a}function Aa(){}
function Ba(a){if(a!=null&&a.Eb!=null)a=a.key;else{var b=Ba[t(a==null?null:a)];if(b!=null)a=b.g?b.g(a):b.call(null,a);else if(b=Ba._,b!=null)a=b.g?b.g(a):b.call(null,a);else throw y("IMapEntry.-key",a);}return a}function Ca(a){if(a!=null&&a.Fb!=null)a=a.G;else{var b=Ca[t(a==null?null:a)];if(b!=null)a=b.g?b.g(a):b.call(null,a);else if(b=Ca._,b!=null)a=b.g?b.g(a):b.call(null,a);else throw y("IMapEntry.-val",a);}return a}function Da(){}
function Ea(a){if(a!=null&&a.Ab!=null)a=a.G;else{var b=Ea[t(a==null?null:a)];if(b!=null)a=b.g?b.g(a):b.call(null,a);else if(b=Ea._,b!=null)a=b.g?b.g(a):b.call(null,a);else throw y("IDeref.-deref",a);}return a}function Fa(){}function Ga(a){if(a!=null&&a.N!=null)a=a.N(a);else{var b=Ga[t(a==null?null:a)];if(b!=null)a=b.g?b.g(a):b.call(null,a);else if(b=Ga._,b!=null)a=b.g?b.g(a):b.call(null,a);else throw y("IMeta.-meta",a);}return a}
function Ha(a,b){if(a!=null&&a.O!=null)a=a.O(a,b);else{var c=Ha[t(a==null?null:a)];if(c!=null)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=Ha._,c!=null)a=c.h?c.h(a,b):c.call(null,a,b);else throw y("IWithMeta.-with-meta",a);}return a}function Ia(){}
var Ka=function(){function a(d,e,g){var h=Ja[t(d==null?null:d)];if(h!=null)return h.m?h.m(d,e,g):h.call(null,d,e,g);h=Ja._;if(h!=null)return h.m?h.m(d,e,g):h.call(null,d,e,g);throw y("IReduce.-reduce",d);}function b(d,e){var g=Ja[t(d==null?null:d)];if(g!=null)return g.h?g.h(d,e):g.call(null,d,e);g=Ja._;if(g!=null)return g.h?g.h(d,e):g.call(null,d,e);throw y("IReduce.-reduce",d);}var c=null;c=function(d,e,g){switch(arguments.length){case 2:return b.call(this,d,e);case 3:return a.call(this,d,e,g)}throw Error("Invalid arity: "+
arguments.length);};c.h=b;c.m=a;return c}(),Ja=function Ja(a){switch(arguments.length){case 2:return Ja.h(arguments[0],arguments[1]);case 3:return Ja.m(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length)].join(""));}};Ja.h=function(a,b){return a!=null&&a.Z!=null?a.Z(a,b):Ka(a,b)};Ja.m=function(a,b,c){return a!=null&&a.$!=null?a.$(a,b,c):Ka(a,b,c)};Ja.ga=3;function La(){}
function Ma(a,b){if(a!=null&&a.gb!=null)a=a.gb(a,b,!0);else{var c=Ma[t(a==null?null:a)];if(c!=null)a=c.m?c.m(a,b,!0):c.call(null,a,b,!0);else if(c=Ma._,c!=null)a=c.m?c.m(a,b,!0):c.call(null,a,b,!0);else throw y("IKVReduce.-kv-reduce",a);}return a}function Na(a,b){if(a!=null&&a.I!=null)a=a.I(a,b);else{var c=Na[t(a==null?null:a)];if(c!=null)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=Na._,c!=null)a=c.h?c.h(a,b):c.call(null,a,b);else throw y("IEquiv.-equiv",a);}return a}
function Oa(a){if(a!=null&&a.M!=null)a=a.M(a);else{var b=Oa[t(a==null?null:a)];if(b!=null)a=b.g?b.g(a):b.call(null,a);else if(b=Oa._,b!=null)a=b.g?b.g(a):b.call(null,a);else throw y("IHash.-hash",a);}return a}function Pa(){}function Qa(a){if(a!=null&&a.T!=null)a=a.T(a);else{var b=Qa[t(a==null?null:a)];if(b!=null)a=b.g?b.g(a):b.call(null,a);else if(b=Qa._,b!=null)a=b.g?b.g(a):b.call(null,a);else throw y("ISeqable.-seq",a);}return a}function Ra(){}function Sa(){}function Ta(){}
function H(a,b){if(a!=null&&a.vb!=null)a=a.vb(a,b);else{var c=H[t(a==null?null:a)];if(c!=null)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=H._,c!=null)a=c.h?c.h(a,b):c.call(null,a,b);else throw y("IWriter.-write",a);}return a}function Ua(){}function Va(a,b,c){if(a!=null&&a.J!=null)a=a.J(a,b,c);else{var d=Va[t(a==null?null:a)];if(d!=null)a=d.m?d.m(a,b,c):d.call(null,a,b,c);else if(d=Va._,d!=null)a=d.m?d.m(a,b,c):d.call(null,a,b,c);else throw y("IPrintWithWriter.-pr-writer",a);}return a}
function Wa(a){if(a!=null&&a.Xa!=null)a=a.Xa(a);else{var b=Wa[t(a==null?null:a)];if(b!=null)a=b.g?b.g(a):b.call(null,a);else if(b=Wa._,b!=null)a=b.g?b.g(a):b.call(null,a);else throw y("IEditableCollection.-as-transient",a);}return a}function Xa(a,b){if(a!=null&&a.Za!=null)a=a.Za(a,b);else{var c=Xa[t(a==null?null:a)];if(c!=null)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=Xa._,c!=null)a=c.h?c.h(a,b):c.call(null,a,b);else throw y("ITransientCollection.-conj!",a);}return a}
function Ya(a){if(a!=null&&a.ib!=null)a=a.ib(a);else{var b=Ya[t(a==null?null:a)];if(b!=null)a=b.g?b.g(a):b.call(null,a);else if(b=Ya._,b!=null)a=b.g?b.g(a):b.call(null,a);else throw y("ITransientCollection.-persistent!",a);}return a}function Za(a,b,c){if(a!=null&&a.Va!=null)a=a.Va(a,b,c);else{var d=Za[t(a==null?null:a)];if(d!=null)a=d.m?d.m(a,b,c):d.call(null,a,b,c);else if(d=Za._,d!=null)a=d.m?d.m(a,b,c):d.call(null,a,b,c);else throw y("ITransientAssociative.-assoc!",a);}return a}
function $a(a){if(a!=null&&a.rb!=null)a=a.rb(a);else{var b=$a[t(a==null?null:a)];if(b!=null)a=b.g?b.g(a):b.call(null,a);else if(b=$a._,b!=null)a=b.g?b.g(a):b.call(null,a);else throw y("IChunk.-drop-first",a);}return a}function ab(a){if(a!=null&&a.mb!=null)a=a.mb(a);else{var b=ab[t(a==null?null:a)];if(b!=null)a=b.g?b.g(a):b.call(null,a);else if(b=ab._,b!=null)a=b.g?b.g(a):b.call(null,a);else throw y("IChunkedSeq.-chunked-first",a);}return a}
function bb(a){if(a!=null&&a.fb!=null)a=a.fb(a);else{var b=bb[t(a==null?null:a)];if(b!=null)a=b.g?b.g(a):b.call(null,a);else if(b=bb._,b!=null)a=b.g?b.g(a):b.call(null,a);else throw y("IChunkedSeq.-chunked-rest",a);}return a}function cb(){}function db(a){if(a!=null&&a.sa!=null)a=a.sa(a);else{var b=db[t(a==null?null:a)];if(b!=null)a=b.g?b.g(a):b.call(null,a);else if(b=db._,b!=null)a=b.g?b.g(a):b.call(null,a);else throw y("IIterable.-iterator",a);}return a}
function eb(a){this.Mb=a;this.j=1073741824;this.A=0}eb.prototype.vb=function(a,b){return this.Mb.append(b)};function fb(a){var b=new ea;a.J(null,new eb(b),new gb(null,5,[hb,!0,ib,!0,jb,!1,kb,!1,lb,null],null));return z.g(b)}var mb=typeof Math!=="undefined"&&typeof Math.imul!=="undefined"?function(a,b){return Math.imul(a,b)}:function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0};function nb(a){a=mb(a|0,-862048943);return mb(a<<15|a>>>-15,461845907)}
function ob(a,b){a=(a|0)^(b|0);return mb(a<<13|a>>>-13,5)+-430675100|0}function pb(a,b){a=(a|0)^b;a=mb(a^a>>>16,-2048144789);a=mb(a^a>>>13,-1028477387);return a^a>>>16}function qb(a){a:{var b=1;for(var c=0;;)if(b<a.length)c=ob(c,nb(a.charCodeAt(b-1)|a.charCodeAt(b)<<16)),b+=2;else{b=c;break a}b=void 0}return pb((a.length&1)===1?b^nb(a.charCodeAt(a.length-1)):b,mb(2,a.length))}var rb={},sb=0;
function tb(a){sb>255&&(rb={},sb=0);if(a==null)return 0;var b=rb[a];if(typeof b==="number")a=b;else{a:if(a!=null)if(b=a.length,b>0){for(var c=0,d=0;;)if(c<b)d=mb(31,d)+a.charCodeAt(c),c+=1;else{b=d;break a}b=void 0}else b=0;else b=0;rb[a]=b;sb+=1;a=b}return a}
function ub(a){if(a!=null&&(a.j&4194304||u===a.Qb))return a.M(null)^0;if(typeof a==="number"){if(isFinite(a)){if(Number.isSafeInteger(a))a=Math.floor(a)%2147483647;else{var b=new Float64Array(1);b[0]=a;b=b.buffer;a=(new DataView(b,0,4)).getInt32();b=(new DataView(b,4,4)).getInt32();a^=b}return a}switch(a){case Infinity:return 2146435072;case -Infinity:return-1048576;default:return 2146959360}}else return a===!0?a=1231:a===!1?a=1237:typeof a==="string"?(a=tb(a),a=a===0?a:pb(ob(0,nb(a)),4)):a=a instanceof
Date?a.valueOf()^0:a==null?0:Oa(a)^0,a}function vb(a,b){return a^b+2654435769+(a<<6)+(a>>2)}function wb(a,b,c,d,e){this.eb=a;this.name=b;this.Aa=c;this.Ta=d;this.ra=e;this.j=2154168321;this.A=4096}f=wb.prototype;f.toString=function(){return this.Aa};f.I=function(a,b){return b instanceof wb?this.Aa===b.Aa:!1};
f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(C(b)))};f.g=function(a){return xb?xb(a,this):yb.call(null,a,this)};f.h=function(a,b){return zb?zb(a,this,b):yb.call(null,a,this,b)};f.N=function(){return this.ra};f.O=function(a,b){return new wb(this.eb,this.name,this.Aa,this.Ta,b)};
f.M=function(){var a=this.Ta;return a!=null?a:this.Ta=a=vb(qb(this.name),tb(this.eb))};f.J=function(a,b){return H(b,this.Aa)};var Ab=function Ab(a){switch(arguments.length){case 1:return Ab.g(arguments[0]);case 2:return Ab.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",z.g(arguments.length)].join(""));}};
Ab.g=function(a){for(;;){if(a instanceof wb)return a;if(typeof a==="string"){var b=a.indexOf("/");return b<1?Ab.h(null,a):Ab.h(a.substring(0,b),a.substring(b+1,a.length))}if(a instanceof I)a=a.va;else throw Error("no conversion to symbol");}};Ab.h=function(a,b){var c=a!=null?[z.g(a),"/",z.g(b)].join(""):b;return new wb(a,b,c,null,null)};Ab.ga=2;function Bb(a){return a!=null?a.A&131072||u===a.Rb?!0:a.A?!1:w(cb,a):w(cb,a)}
function J(a){if(a==null)return null;if(a!=null&&(a.j&8388608||u===a.Jb))return a.T(null);if(ha(a)||typeof a==="string")return a.length===0?null:new M(a,0,null);if(a!=null&&a[ja]!=null)return a=(a!==null&&ja in a?a[ja]:void 0).call(a),Cb.g?Cb.g(a):Cb.call(null,a);if(w(Pa,a))return Qa(a);throw Error([z.g(a)," is not ISeqable"].join(""));}function N(a){if(a==null)return null;if(a!=null&&(a.j&64||u===a.hb))return a.aa(null);a=J(a);return a==null?null:E(a)}
function Db(a){return a!=null?a!=null&&(a.j&64||u===a.hb)?a.fa(null):(a=J(a))?a.fa(null):O:O}function P(a){return a==null?null:a!=null&&(a.j&128||u===a.Ya)?a.S(null):J(Db(a))}var R=function R(a){switch(arguments.length){case 1:return R.g(arguments[0]);case 2:return R.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return R.R(arguments[0],arguments[1],2<c.length?new M(c.slice(2),0,null):null)}};R.g=function(){return!0};
R.h=function(a,b){return a==null?b==null:a===b||Na(a,b)};R.R=function(a,b,c){for(;;){if(R.h(a,b))if(P(c)){a=b;b=N(c);c=P(c);continue}else return R.h(b,N(c));else return!1;break}};R.ba=function(a){var b=N(a),c=P(a);a=N(c);c=P(c);return this.R(b,a,c)};R.ga=2;function Eb(a){this.D=a}Eb.prototype.next=function(){if(this.D!=null){var a=N(this.D);this.D=P(this.D);return{value:a,done:!1}}return{value:null,done:!0}};function S(a){return new Eb(J(a))}
function Fb(a,b){this.value=a;this.wb=b;this.jb=null;this.j=8388672;this.A=0}Fb.prototype.T=function(){return this};Fb.prototype.aa=function(){return this.value};Fb.prototype.fa=function(){this.jb==null&&(this.jb=Cb.g?Cb.g(this.wb):Cb.call(null,this.wb));return this.jb};function Cb(a){var b=a.next();return v(b.done)?null:new Fb(b.value,a)}function Gb(a){var b=0,c=1;for(a=J(a);;)if(a!=null)b+=1,c=mb(31,c)+ub(N(a))|0,a=P(a);else return pb(ob(0,nb(c)),b)}var Hb=pb(ob(0,nb(1)),0);
function Ib(a){var b=0,c=0;for(a=J(a);;)if(a!=null)b+=1,c=c+ub(N(a))|0,a=P(a);else return pb(ob(0,nb(c)),b)}var Jb=pb(ob(0,nb(0)),0);ka["null"]=!0;la["null"]=function(){return 0};Date.prototype.I=function(a,b){return b instanceof Date&&this.valueOf()===b.valueOf()};Na.number=function(a,b){return a===b};Fa["function"]=!0;Ga["function"]=function(){return null};Oa._=function(a){return Object.prototype.hasOwnProperty.call(a,aa)&&a[aa]||(a[aa]=++ba)};Oa.symbol=function(a){return ub(a.toString())};
function Kb(){this.G=!1;this.j=32768;this.A=0}Kb.prototype.Ab=function(){return this.G};function Lb(a){return a instanceof Kb}function Mb(a){return Ea(a)}function Nb(a,b){var c=a.length;if(a.length===0)return b.F?b.F():b.call(null);for(var d=a[0],e=1;;)if(e<c){var g=a[e];d=b.h?b.h(d,g):b.call(null,d,g);if(Lb(d))return Ea(d);e+=1}else return d}function Ob(a,b,c){var d=a.length,e=c;for(c=0;;)if(c<d){var g=a[c];e=b.h?b.h(e,g):b.call(null,e,g);if(Lb(e))return Ea(e);c+=1}else return e}
function Pb(a,b,c,d){for(var e=a.length;;)if(d<e){var g=a[d];c=b.h?b.h(c,g):b.call(null,c,g);if(Lb(c))return Ea(c);d+=1}else return c}function Qb(a){return a!=null?a.j&2||u===a.zb?!0:a.j?!1:w(ka,a):w(ka,a)}function Rb(a){return a!=null?a.j&16||u===a.tb?!0:a.j?!1:w(pa,a):w(pa,a)}function T(a,b,c){var d=U.g?U.g(a):U.call(null,a);if(c>=d)return-1;!(c>0)&&c<0&&(c+=d,c=0>c?0:c);for(;;)if(c<d){if(R.h(Sb?Sb(a,c):Tb.call(null,a,c),b))return c;c+=1}else return-1}
function V(a,b,c){var d=U.g?U.g(a):U.call(null,a);if(d===0)return-1;c>0?(--d,c=d<c?d:c):c=c<0?d+c:c;for(;;)if(c>=0){if(R.h(Sb?Sb(a,c):Tb.call(null,a,c),b))return c;--c}else return-1}function Ub(a,b){this.i=a;this.o=b}Ub.prototype.ia=function(){return this.o<this.i.length};Ub.prototype.next=function(){var a=this.i[this.o];this.o+=1;return a};function M(a,b,c){this.i=a;this.o=b;this.u=c;this.j=166592766;this.A=401408}f=M.prototype;f.toString=function(){return fb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,U.g?U.g(this):U.call(null,this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.X=function(a,b){a=b+this.o;if(0<=a&&a<this.i.length)return this.i[a];throw Error("Index out of bounds");};f.la=function(a,b,c){a=b+this.o;return 0<=a&&a<this.i.length?this.i[a]:c};
f.sa=function(){return new Ub(this.i,this.o)};f.N=function(){return this.u};f.S=function(){return this.o+1<this.i.length?new M(this.i,this.o+1,null):null};f.V=function(){var a=this.i.length-this.o;return 0>a?0:a};f.M=function(){return Gb(this)};f.I=function(a,b){return Vb.h?Vb.h(this,b):Vb.call(null,this,b)};f.W=function(){return O};f.Z=function(a,b){return Pb(this.i,b,this.i[this.o],this.o+1)};f.$=function(a,b,c){return Pb(this.i,b,c,this.o)};f.aa=function(){return this.i[this.o]};
f.fa=function(){return this.o+1<this.i.length?new M(this.i,this.o+1,null):O};f.T=function(){return this.o<this.i.length?this:null};f.O=function(a,b){return b===this.u?this:new M(this.i,this.o,b)};f.U=function(a,b){return W.h?W.h(b,this):W.call(null,b,this)};M.prototype[ja]=function(){return S(this)};function Wb(a){return 0<a.length?new M(a,0,null):null}Na._=function(a,b){return a===b};
var Xb=function Xb(a){switch(arguments.length){case 0:return Xb.F();case 1:return Xb.g(arguments[0]);case 2:return Xb.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Xb.R(arguments[0],arguments[1],2<c.length?new M(c.slice(2),0,null):null)}};Xb.F=function(){return Yb};Xb.g=function(a){return a};Xb.h=function(a,b){return a!=null?oa(a,b):new Zb(null,b,null,1,null)};
Xb.R=function(a,b,c){for(;;)if(v(c))a=Xb.h(a,b),b=N(c),c=P(c);else return Xb.h(a,b)};Xb.ba=function(a){var b=N(a),c=P(a);a=N(c);c=P(c);return this.R(b,a,c)};Xb.ga=2;function U(a){if(a!=null)if(a!=null&&(a.j&2||u===a.zb))a=a.V(null);else if(ha(a))a=a.length;else if(typeof a==="string")a=a.length;else if(a!=null&&(a.j&8388608||u===a.Jb))a:{a=J(a);for(var b=0;;){if(Qb(a)){a=b+la(a);break a}a=P(a);b+=1}a=void 0}else a=la(a);else a=0;return a}
function $b(a,b,c){for(;;){if(a==null)return c;if(b===0)return J(a)?N(a):c;if(Rb(a))return D(a,b,c);if(J(a))a=P(a),--b;else return c}}function Tb(a){switch(arguments.length){case 2:return Sb(arguments[0],arguments[1]);case 3:return ac(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length)].join(""));}}
function Sb(a,b){if(typeof b!=="number")throw Error("Index argument to nth must be a number");if(a==null)return a;if(a!=null&&(a.j&16||u===a.tb))return a.X(null,b);if(ha(a)){if(-1<b&&b<a.length)return a[b|0];throw Error("Index out of bounds");}if(typeof a==="string"){if(-1<b&&b<a.length)return a.charAt(b|0);throw Error("Index out of bounds");}if(a!=null&&(a.j&64||u===a.hb)||a!=null&&(a.j&16777216||u===a.ub)){if(b<0)throw Error("Index out of bounds");a:{for(;;){if(a==null)throw Error("Index out of bounds");
if(b===0){if(J(a)){a=N(a);break a}throw Error("Index out of bounds");}if(Rb(a)){a=D(a,b);break a}if(J(a))a=P(a),--b;else throw Error("Index out of bounds");}a=void 0}return a}if(w(pa,a))return D(a,b);throw Error(["nth not supported on this type ",z.g(ia(a==null?null:a.constructor))].join(""));}
function ac(a,b,c){if(typeof b!=="number")throw Error("Index argument to nth must be a number.");if(a==null)return c;if(a!=null&&(a.j&16||u===a.tb))return a.la(null,b,c);if(ha(a))return-1<b&&b<a.length?a[b|0]:c;if(typeof a==="string")return-1<b&&b<a.length?a.charAt(b|0):c;if(a!=null&&(a.j&64||u===a.hb)||a!=null&&(a.j&16777216||u===a.ub))return b<0?c:$b(a,b,c);if(w(pa,a))return D(a,b,c);throw Error(["nth not supported on this type ",z.g(ia(a==null?null:a.constructor))].join(""));}
function yb(a){switch(arguments.length){case 2:return xb(arguments[0],arguments[1]);case 3:return zb(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length)].join(""));}}function xb(a,b){return a==null?null:a!=null&&(a.j&256||u===a.Db)?a.ka(null,b):ha(a)?b!=null&&b<a.length?a[b|0]:null:typeof a==="string"?b!=null&&-1<b&&b<a.length?a.charAt(b|0):null:w(ta,a)?ua(a,b):null}
function zb(a,b,c){return a!=null?a!=null&&(a.j&256||u===a.Db)?a.H(null,b,c):ha(a)?b!=null&&-1<b&&b<a.length?a[b|0]:c:typeof a==="string"?b!=null&&-1<b&&b<a.length?a.charAt(b|0):c:w(ta,a)?ua(a,b,c):c:c}var bc=function bc(a){switch(arguments.length){case 3:return bc.m(arguments[0],arguments[1],arguments[2]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return bc.R(arguments[0],arguments[1],arguments[2],3<c.length?new M(c.slice(3),0,null):null)}};
bc.m=function(a,b,c){if(a!=null&&(a.j&512||u===a.yb))a=a.xa(null,b,c);else if(a!=null)a=za(a,b,c);else{a=[b,c];b=a.length;c=1===(b&1);var d;if(!(d=c))a:{for(d=0;;)if(d<a.length){var e;b:{for(e=0;;)if(e<d){var g=cc(a[d],a[e]);if(g){e=g;break b}e=2+e}else{e=!1;break b}e=void 0}if(e){d=e;break a}d=2+d}else{d=!1;break a}d=void 0}a=d?dc(a,c):new gb(null,b/2,a,null)}return a};bc.R=function(a,b,c,d){for(;;)if(a=bc.m(a,b,c),v(d))b=N(d),c=N(P(d)),d=P(P(d));else return a};
bc.ba=function(a){var b=N(a),c=P(a);a=N(c);var d=P(c);c=N(d);d=P(d);return this.R(b,a,c,d)};bc.ga=3;function ec(a,b){this.s=a;this.u=b;this.j=393217;this.A=0}f=ec.prototype;f.N=function(){return this.u};f.O=function(a,b){return new ec(this.s,b)};
f.call=function(a){switch(arguments.length-1){case 0:return this.F();case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);case 3:return this.m(arguments[1],arguments[2],arguments[3]);case 4:return this.ea(arguments[1],arguments[2],arguments[3],arguments[4]);case 5:return this.ua(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);case 6:return this.Na(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6]);case 7:return this.Oa(arguments[1],
arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7]);case 8:return this.Pa(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8]);case 9:return this.Qa(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9]);case 10:return this.Ca(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10]);
case 11:return this.Da(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11]);case 12:return this.Ea(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12]);case 13:return this.Fa(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],
arguments[11],arguments[12],arguments[13]);case 14:return this.Ga(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14]);case 15:return this.Ha(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15]);case 16:return this.Ia(arguments[1],
arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16]);case 17:return this.Ja(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16],arguments[17]);case 18:return this.Ka(arguments[1],arguments[2],
arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16],arguments[17],arguments[18]);case 19:return this.La(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16],arguments[17],arguments[18],arguments[19]);case 20:return this.Ma(arguments[1],
arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16],arguments[17],arguments[18],arguments[19],arguments[20]);case 21:return this.nb(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16],arguments[17],
arguments[18],arguments[19],arguments[20],arguments[21]);default:throw Error(["Invalid arity: ",z.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(C(b)))};f.F=function(){return this.s.F?this.s.F():this.s.call(null)};f.g=function(a){return this.s.g?this.s.g(a):this.s.call(null,a)};f.h=function(a,b){return this.s.h?this.s.h(a,b):this.s.call(null,a,b)};f.m=function(a,b,c){return this.s.m?this.s.m(a,b,c):this.s.call(null,a,b,c)};
f.ea=function(a,b,c,d){return this.s.ea?this.s.ea(a,b,c,d):this.s.call(null,a,b,c,d)};f.ua=function(a,b,c,d,e){return this.s.ua?this.s.ua(a,b,c,d,e):this.s.call(null,a,b,c,d,e)};f.Na=function(a,b,c,d,e,g){return this.s.Na?this.s.Na(a,b,c,d,e,g):this.s.call(null,a,b,c,d,e,g)};f.Oa=function(a,b,c,d,e,g,h){return this.s.Oa?this.s.Oa(a,b,c,d,e,g,h):this.s.call(null,a,b,c,d,e,g,h)};f.Pa=function(a,b,c,d,e,g,h,k){return this.s.Pa?this.s.Pa(a,b,c,d,e,g,h,k):this.s.call(null,a,b,c,d,e,g,h,k)};
f.Qa=function(a,b,c,d,e,g,h,k,l){return this.s.Qa?this.s.Qa(a,b,c,d,e,g,h,k,l):this.s.call(null,a,b,c,d,e,g,h,k,l)};f.Ca=function(a,b,c,d,e,g,h,k,l,m){return this.s.Ca?this.s.Ca(a,b,c,d,e,g,h,k,l,m):this.s.call(null,a,b,c,d,e,g,h,k,l,m)};f.Da=function(a,b,c,d,e,g,h,k,l,m,n){return this.s.Da?this.s.Da(a,b,c,d,e,g,h,k,l,m,n):this.s.call(null,a,b,c,d,e,g,h,k,l,m,n)};f.Ea=function(a,b,c,d,e,g,h,k,l,m,n,p){return this.s.Ea?this.s.Ea(a,b,c,d,e,g,h,k,l,m,n,p):this.s.call(null,a,b,c,d,e,g,h,k,l,m,n,p)};
f.Fa=function(a,b,c,d,e,g,h,k,l,m,n,p,q){return this.s.Fa?this.s.Fa(a,b,c,d,e,g,h,k,l,m,n,p,q):this.s.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q)};f.Ga=function(a,b,c,d,e,g,h,k,l,m,n,p,q,r){return this.s.Ga?this.s.Ga(a,b,c,d,e,g,h,k,l,m,n,p,q,r):this.s.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,r)};f.Ha=function(a,b,c,d,e,g,h,k,l,m,n,p,q,r,x){return this.s.Ha?this.s.Ha(a,b,c,d,e,g,h,k,l,m,n,p,q,r,x):this.s.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,r,x)};
f.Ia=function(a,b,c,d,e,g,h,k,l,m,n,p,q,r,x,A){return this.s.Ia?this.s.Ia(a,b,c,d,e,g,h,k,l,m,n,p,q,r,x,A):this.s.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,r,x,A)};f.Ja=function(a,b,c,d,e,g,h,k,l,m,n,p,q,r,x,A,B){return this.s.Ja?this.s.Ja(a,b,c,d,e,g,h,k,l,m,n,p,q,r,x,A,B):this.s.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,r,x,A,B)};f.Ka=function(a,b,c,d,e,g,h,k,l,m,n,p,q,r,x,A,B,F){return this.s.Ka?this.s.Ka(a,b,c,d,e,g,h,k,l,m,n,p,q,r,x,A,B,F):this.s.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,r,x,A,B,F)};
f.La=function(a,b,c,d,e,g,h,k,l,m,n,p,q,r,x,A,B,F,K){return this.s.La?this.s.La(a,b,c,d,e,g,h,k,l,m,n,p,q,r,x,A,B,F,K):this.s.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,r,x,A,B,F,K)};f.Ma=function(a,b,c,d,e,g,h,k,l,m,n,p,q,r,x,A,B,F,K,Q){return this.s.Ma?this.s.Ma(a,b,c,d,e,g,h,k,l,m,n,p,q,r,x,A,B,F,K,Q):this.s.call(null,a,b,c,d,e,g,h,k,l,m,n,p,q,r,x,A,B,F,K,Q)};
f.nb=function(a,b,c,d,e,g,h,k,l,m,n,p,q,r,x,A,B,F,K,Q,ca){return fc.nb?fc.nb(this.s,a,b,c,d,e,g,h,k,l,m,n,p,q,r,x,A,B,F,K,new M([Q,ca],0,null)):fc.call(null,this.s,a,b,c,d,e,g,h,k,l,m,n,p,q,r,x,A,B,F,K,Q,ca)};function gc(a,b){return typeof a==="function"?new ec(a,b):a==null?null:Ha(a,b)}function hc(a){var b=a!=null;return(b?a!=null?a.j&131072||u===a.Gb||(a.j?0:w(Fa,a)):w(Fa,a):b)?Ga(a):null}function ic(a){return a!=null?a.j&16777216||u===a.ub?!0:a.j?!1:w(Ra,a):w(Ra,a)}
function jc(a){return a==null?!1:a!=null?a.j&1024||u===a.Tb?!0:a.j?!1:w(Aa,a):w(Aa,a)}function kc(a){return a!=null?a.j&67108864||u===a.Vb?!0:a.j?!1:w(Ta,a):w(Ta,a)}function lc(a){return a!=null?a.j&16384||u===a.Wb?!0:a.j?!1:w(Da,a):w(Da,a)}function mc(a){return a!=null?a.A&512||u===a.Ob?!0:!1:!1}function nc(a,b,c,d,e){for(;;){if(e===0)return c;c[d]=a[b];d+=1;--e;b+=1}}var oc={};function pc(a){return a==null?!1:a===!1?!1:!0}
function qc(a,b){return a!=null&&(a.j&512||u===a.yb)?a.Ua(null,b):w(xa,a)?ya(a,b):zb(a,b,oc)===oc?!1:!0}function rc(a,b){var c=J(b);return c?(b=N(c),c=P(c),sc?sc(a,b,c):tc.call(null,a,b,c)):a.F?a.F():a.call(null)}function uc(a,b,c){for(c=J(c);;)if(c){var d=N(c);b=a.h?a.h(b,d):a.call(null,b,d);if(Lb(b))return Ea(b);c=P(c)}else return b}
function vc(a,b){a=db(a);if(v(a.ia()))for(var c=a.next();;)if(a.ia()){var d=a.next();c=b.h?b.h(c,d):b.call(null,c,d);if(Lb(c))return Ea(c)}else return c;else return b.F?b.F():b.call(null)}function wc(a,b,c){for(a=db(a);;)if(a.ia()){var d=a.next();c=b.h?b.h(c,d):b.call(null,c,d);if(Lb(c))return Ea(c)}else return c}
function tc(a){switch(arguments.length){case 2:var b=arguments[0],c=arguments[1];return c!=null&&(c.j&524288||u===c.Ib)?c.Z(null,b):ha(c)?Nb(c,b):typeof c==="string"?Nb(c,b):w(Ia,c)?Ja(c,b):Bb(c)?vc(c,b):rc(b,c);case 3:return sc(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length)].join(""));}}
function sc(a,b,c){return c!=null&&(c.j&524288||u===c.Ib)?c.$(null,a,b):ha(c)?Ob(c,a,b):typeof c==="string"?Ob(c,a,b):w(Ia,c)?Ja(c,a,b):Bb(c)?wc(c,a,b):uc(a,b,c)}function xc(a,b){return(b!=null?b.j&1048576||u===b.Cb||(b.j?0:w(La,b)):w(La,b))?Ma(b,a):sc(function(c,d){var e=Ba(d);d=Ca(d);return a.m?a.m(c,e,d):a.call(null,c,e,d)},!0,b)}function yc(a){return a}function zc(a){a=(a-a%2)/2;return a>=0?Math.floor(a):Math.ceil(a)}
function Ac(a){a-=a>>1&1431655765;a=(a&858993459)+(a>>2&858993459);return(a+(a>>4)&252645135)*16843009>>24}var z=function z(a){switch(arguments.length){case 0:return z.F();case 1:return z.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return z.R(arguments[0],1<c.length?new M(c.slice(1),0,null):null)}};z.F=function(){return""};z.g=function(a){return a==null?"":[a].join("")};
z.R=function(a,b){for(a=new ea(z.g(a));;)if(v(b))a=a.append(z.g(N(b))),b=P(b);else return a.toString()};z.ba=function(a){var b=N(a);a=P(a);return this.R(b,a)};z.ga=1;function Vb(a,b){if(ic(b))if(Qb(a)&&Qb(b)&&U(a)!==U(b))a=!1;else a:{a=J(a);for(b=J(b);;){if(a==null){a=b==null;break a}if(b!=null&&R.h(N(a),N(b)))a=P(a),b=P(b);else{a=!1;break a}}a=void 0}else a=null;return pc(a)}function Zb(a,b,c,d,e){this.u=a;this.first=b;this.wa=c;this.count=d;this.v=e;this.j=65937646;this.A=8192}f=Zb.prototype;
f.toString=function(){return fb(this)};f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,this.count)}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.N=function(){return this.u};f.S=function(){return this.count===1?null:this.wa};f.V=function(){return this.count};f.M=function(){var a=this.v;return a!=null?a:this.v=a=Gb(this)};f.I=function(a,b){return Vb(this,b)};
f.W=function(){return Ha(O,this.u)};f.Z=function(a,b){return rc(b,this)};f.$=function(a,b,c){return uc(b,c,this)};f.aa=function(){return this.first};f.fa=function(){return this.count===1?O:this.wa};f.T=function(){return this};f.O=function(a,b){return b===this.u?this:new Zb(b,this.first,this.wa,this.count,this.v)};f.U=function(a,b){return new Zb(this.u,b,this,this.count+1,null)};Zb.prototype[ja]=function(){return S(this)};function Bc(a){this.u=a;this.j=65937614;this.A=8192}f=Bc.prototype;
f.toString=function(){return fb(this)};f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,U(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.N=function(){return this.u};f.S=function(){return null};f.V=function(){return 0};f.M=function(){return Hb};f.I=function(a,b){return(b!=null?b.j&33554432||u===b.Sb||(b.j?0:w(Sa,b)):w(Sa,b))||ic(b)?J(b)==null:!1};f.W=function(){return this};
f.Z=function(a,b){return rc(b,this)};f.$=function(a,b,c){return uc(b,c,this)};f.aa=function(){return null};f.fa=function(){return O};f.T=function(){return null};f.O=function(a,b){return b===this.u?this:new Bc(b)};f.U=function(a,b){return new Zb(this.u,b,null,1,null)};var O=new Bc(null);Bc.prototype[ja]=function(){return S(this)};function Cc(a,b,c,d){this.u=a;this.first=b;this.wa=c;this.v=d;this.j=65929452;this.A=8192}f=Cc.prototype;f.toString=function(){return fb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,U(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.N=function(){return this.u};f.S=function(){return this.wa==null?null:J(this.wa)};f.M=function(){var a=this.v;return a!=null?a:this.v=a=Gb(this)};f.I=function(a,b){return Vb(this,b)};f.W=function(){return O};
f.Z=function(a,b){return rc(b,this)};f.$=function(a,b,c){return uc(b,c,this)};f.aa=function(){return this.first};f.fa=function(){return this.wa==null?O:this.wa};f.T=function(){return this};f.O=function(a,b){return b===this.u?this:new Cc(b,this.first,this.wa,this.v)};f.U=function(a,b){return new Cc(null,b,this,null)};Cc.prototype[ja]=function(){return S(this)};function W(a,b){return b==null?new Zb(null,a,null,1,null):b!=null&&(b.j&64||u===b.hb)?new Cc(null,a,b,null):new Cc(null,a,J(b),null)}
function I(a,b,c,d){this.eb=a;this.name=b;this.va=c;this.Ta=d;this.j=2153775105;this.A=4096}f=I.prototype;f.toString=function(){return[":",z.g(this.va)].join("")};f.I=function(a,b){return b instanceof I?this.va===b.va:!1};f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(C(b)))};
f.g=function(a){return xb(a,this)};f.h=function(a,b){return zb(a,this,b)};f.M=function(){var a=this.Ta;return a!=null?a:this.Ta=a=vb(qb(this.name),tb(this.eb))+2654435769|0};f.J=function(a,b){return H(b,[":",z.g(this.va)].join(""))};function Dc(a){if(a!=null&&(a.A&4096||u===a.Hb))return a.eb;throw Error(["Doesn't support namespace: ",z.g(a)].join(""));}
var Ec=function Ec(a){switch(arguments.length){case 1:return Ec.g(arguments[0]);case 2:return Ec.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",z.g(arguments.length)].join(""));}};Ec.g=function(a){if(a instanceof I)return a;if(a instanceof wb)return new I(Dc(a),Fc.g?Fc.g(a):Fc.call(null,a),a.Aa,null);if(R.h("/",a))return new I(null,a,a,null);if(typeof a==="string"){var b=a.split("/");return b.length===2?new I(b[0],b[1],a,null):new I(null,b[0],a,null)}return null};
Ec.h=function(a,b){a=a instanceof I?Fc.g?Fc.g(a):Fc.call(null,a):a instanceof wb?Fc.g?Fc.g(a):Fc.call(null,a):a;b=b instanceof I?Fc.g?Fc.g(b):Fc.call(null,b):b instanceof wb?Fc.g?Fc.g(b):Fc.call(null,b):b;return new I(a,b,[v(a)?[z.g(a),"/"].join(""):null,z.g(b)].join(""),null)};Ec.ga=2;function Gc(a,b,c){this.u=a;this.$a=b;this.D=null;this.v=c;this.j=32374988;this.A=1}f=Gc.prototype;f.toString=function(){return fb(this)};
function Hc(a){if(a.$a!=null){for(var b=a.$a.F?a.$a.F():a.$a.call(null);;)if(b instanceof Gc)b=Hc(b);else{a.D=J(b);break}a.$a=null}return a.D}f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,U(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.N=function(){return this.u};f.S=function(){Hc(this);return this.D==null?null:sa(this.D)};f.M=function(){var a=this.v;return a!=null?a:this.v=a=Gb(this)};f.I=function(a,b){return Vb(this,b)};f.W=function(){return Ha(O,this.u)};
f.Z=function(a,b){return rc(b,this)};f.$=function(a,b,c){return uc(b,c,this)};f.aa=function(){Hc(this);return this.D==null?null:E(this.D)};f.fa=function(){Hc(this);return this.D!=null?G(this.D):O};f.T=function(){return Hc(this)};f.O=function(a,b){var c=this;return b===this.u?c:new Gc(b,function(){return Hc(c)},this.v)};f.U=function(a,b){return W(b,this)};Gc.prototype[ja]=function(){return S(this)};function Ic(a){this.lb=a;this.end=0;this.j=2;this.A=0}
Ic.prototype.add=function(a){this.lb[this.end]=a;return this.end+=1};Ic.prototype.ta=function(){var a=new Jc(this.lb,0,this.end);this.lb=null;return a};Ic.prototype.V=function(){return this.end};function Jc(a,b,c){this.i=a;this.P=b;this.end=c;this.j=524306;this.A=0}f=Jc.prototype;f.V=function(){return this.end-this.P};f.X=function(a,b){return this.i[this.P+b]};f.la=function(a,b,c){return b>=0&&b<this.end-this.P?this.i[this.P+b]:c};
f.rb=function(){if(this.P===this.end)throw Error("-drop-first of empty chunk");return new Jc(this.i,this.P+1,this.end)};f.Z=function(a,b){return Pb(this.i,b,this.i[this.P],this.P+1)};f.$=function(a,b,c){return Pb(this.i,b,c,this.P)};function Kc(a,b,c,d){this.ta=a;this.oa=b;this.u=c;this.v=d;this.j=31850732;this.A=1536}f=Kc.prototype;f.toString=function(){return fb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,U(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.N=function(){return this.u};f.S=function(){return la(this.ta)>1?new Kc($a(this.ta),this.oa,null,null):this.oa==null?null:Qa(this.oa)};f.M=function(){var a=this.v;return a!=null?a:this.v=a=Gb(this)};
f.I=function(a,b){return Vb(this,b)};f.W=function(){return O};f.aa=function(){return D(this.ta,0)};f.fa=function(){return la(this.ta)>1?new Kc($a(this.ta),this.oa,null,null):this.oa==null?O:this.oa};f.T=function(){return this};f.mb=function(){return this.ta};f.fb=function(){return this.oa==null?O:this.oa};f.O=function(a,b){return b===this.u?this:new Kc(this.ta,this.oa,b,this.v)};f.U=function(a,b){return W(b,this)};f.sb=function(){return this.oa==null?null:this.oa};Kc.prototype[ja]=function(){return S(this)};
function Lc(a,b){return la(a)===0?b:new Kc(a,b,null,null)}function Mc(a,b){a.add(b)}function Nc(a,b){if(Qb(b))return U(b);var c=0;for(b=J(b);;)if(b!=null&&c<a)c+=1,b=P(b);else return c}var Oc=function Oc(a){if(a==null)return null;var c=P(a);return c==null?J(N(a)):W(N(a),Oc.g?Oc.g(c):Oc.call(null,c))};
function Pc(a,b,c){var d=J(c);if(b===0)return a.F?a.F():a.call(null);c=E(d);var e=G(d);if(b===1)return a.g?a.g(c):a.call(null,c);d=E(e);var g=G(e);if(b===2)return a.h?a.h(c,d):a.call(null,c,d);e=E(g);var h=G(g);if(b===3)return a.m?a.m(c,d,e):a.call(null,c,d,e);g=E(h);var k=G(h);if(b===4)return a.ea?a.ea(c,d,e,g):a.call(null,c,d,e,g);h=E(k);var l=G(k);if(b===5)return a.ua?a.ua(c,d,e,g,h):a.call(null,c,d,e,g,h);k=E(l);var m=G(l);if(b===6)return a.Na?a.Na(c,d,e,g,h,k):a.call(null,c,d,e,g,h,k);l=E(m);
var n=G(m);if(b===7)return a.Oa?a.Oa(c,d,e,g,h,k,l):a.call(null,c,d,e,g,h,k,l);m=E(n);var p=G(n);if(b===8)return a.Pa?a.Pa(c,d,e,g,h,k,l,m):a.call(null,c,d,e,g,h,k,l,m);n=E(p);var q=G(p);if(b===9)return a.Qa?a.Qa(c,d,e,g,h,k,l,m,n):a.call(null,c,d,e,g,h,k,l,m,n);p=E(q);var r=G(q);if(b===10)return a.Ca?a.Ca(c,d,e,g,h,k,l,m,n,p):a.call(null,c,d,e,g,h,k,l,m,n,p);q=E(r);var x=G(r);if(b===11)return a.Da?a.Da(c,d,e,g,h,k,l,m,n,p,q):a.call(null,c,d,e,g,h,k,l,m,n,p,q);r=E(x);var A=G(x);if(b===12)return a.Ea?
a.Ea(c,d,e,g,h,k,l,m,n,p,q,r):a.call(null,c,d,e,g,h,k,l,m,n,p,q,r);x=E(A);var B=G(A);if(b===13)return a.Fa?a.Fa(c,d,e,g,h,k,l,m,n,p,q,r,x):a.call(null,c,d,e,g,h,k,l,m,n,p,q,r,x);A=E(B);var F=G(B);if(b===14)return a.Ga?a.Ga(c,d,e,g,h,k,l,m,n,p,q,r,x,A):a.call(null,c,d,e,g,h,k,l,m,n,p,q,r,x,A);B=E(F);var K=G(F);if(b===15)return a.Ha?a.Ha(c,d,e,g,h,k,l,m,n,p,q,r,x,A,B):a.call(null,c,d,e,g,h,k,l,m,n,p,q,r,x,A,B);F=E(K);var Q=G(K);if(b===16)return a.Ia?a.Ia(c,d,e,g,h,k,l,m,n,p,q,r,x,A,B,F):a.call(null,
c,d,e,g,h,k,l,m,n,p,q,r,x,A,B,F);K=E(Q);var ca=G(Q);if(b===17)return a.Ja?a.Ja(c,d,e,g,h,k,l,m,n,p,q,r,x,A,B,F,K):a.call(null,c,d,e,g,h,k,l,m,n,p,q,r,x,A,B,F,K);Q=E(ca);var va=G(ca);if(b===18)return a.Ka?a.Ka(c,d,e,g,h,k,l,m,n,p,q,r,x,A,B,F,K,Q):a.call(null,c,d,e,g,h,k,l,m,n,p,q,r,x,A,B,F,K,Q);ca=E(va);va=G(va);if(b===19)return a.La?a.La(c,d,e,g,h,k,l,m,n,p,q,r,x,A,B,F,K,Q,ca):a.call(null,c,d,e,g,h,k,l,m,n,p,q,r,x,A,B,F,K,Q,ca);var Ld=E(va);G(va);if(b===20)return a.Ma?a.Ma(c,d,e,g,h,k,l,m,n,p,q,r,
x,A,B,F,K,Q,ca,Ld):a.call(null,c,d,e,g,h,k,l,m,n,p,q,r,x,A,B,F,K,Q,ca,Ld);throw Error("Only up to 20 arguments supported on functions");}function Qc(a){return a!=null&&(a.j&128||u===a.Ya)?a.S(null):J(Db(a))}function Rc(a,b,c){return c==null?a.g?a.g(b):a.call(a,b):Sc(a,b,E(c),Qc(c))}function Sc(a,b,c,d){return d==null?a.h?a.h(b,c):a.call(a,b,c):Tc(a,b,c,E(d),Qc(d))}function Tc(a,b,c,d,e){return e==null?a.m?a.m(b,c,d):a.call(a,b,c,d):Uc(a,b,c,d,E(e),Qc(e))}
function Uc(a,b,c,d,e,g){if(g==null)return a.ea?a.ea(b,c,d,e):a.call(a,b,c,d,e);var h=E(g),k=P(g);if(k==null)return a.ua?a.ua(b,c,d,e,h):a.call(a,b,c,d,e,h);g=E(k);var l=P(k);if(l==null)return a.Na?a.Na(b,c,d,e,h,g):a.call(a,b,c,d,e,h,g);k=E(l);var m=P(l);if(m==null)return a.Oa?a.Oa(b,c,d,e,h,g,k):a.call(a,b,c,d,e,h,g,k);l=E(m);var n=P(m);if(n==null)return a.Pa?a.Pa(b,c,d,e,h,g,k,l):a.call(a,b,c,d,e,h,g,k,l);m=E(n);var p=P(n);if(p==null)return a.Qa?a.Qa(b,c,d,e,h,g,k,l,m):a.call(a,b,c,d,e,h,g,k,l,
m);n=E(p);var q=P(p);if(q==null)return a.Ca?a.Ca(b,c,d,e,h,g,k,l,m,n):a.call(a,b,c,d,e,h,g,k,l,m,n);p=E(q);var r=P(q);if(r==null)return a.Da?a.Da(b,c,d,e,h,g,k,l,m,n,p):a.call(a,b,c,d,e,h,g,k,l,m,n,p);q=E(r);var x=P(r);if(x==null)return a.Ea?a.Ea(b,c,d,e,h,g,k,l,m,n,p,q):a.call(a,b,c,d,e,h,g,k,l,m,n,p,q);r=E(x);var A=P(x);if(A==null)return a.Fa?a.Fa(b,c,d,e,h,g,k,l,m,n,p,q,r):a.call(a,b,c,d,e,h,g,k,l,m,n,p,q,r);x=E(A);var B=P(A);if(B==null)return a.Ga?a.Ga(b,c,d,e,h,g,k,l,m,n,p,q,r,x):a.call(a,b,
c,d,e,h,g,k,l,m,n,p,q,r,x);A=E(B);var F=P(B);if(F==null)return a.Ha?a.Ha(b,c,d,e,h,g,k,l,m,n,p,q,r,x,A):a.call(a,b,c,d,e,h,g,k,l,m,n,p,q,r,x,A);B=E(F);var K=P(F);if(K==null)return a.Ia?a.Ia(b,c,d,e,h,g,k,l,m,n,p,q,r,x,A,B):a.call(a,b,c,d,e,h,g,k,l,m,n,p,q,r,x,A,B);F=E(K);var Q=P(K);if(Q==null)return a.Ja?a.Ja(b,c,d,e,h,g,k,l,m,n,p,q,r,x,A,B,F):a.call(a,b,c,d,e,h,g,k,l,m,n,p,q,r,x,A,B,F);K=E(Q);var ca=P(Q);if(ca==null)return a.Ka?a.Ka(b,c,d,e,h,g,k,l,m,n,p,q,r,x,A,B,F,K):a.call(a,b,c,d,e,h,g,k,l,m,
n,p,q,r,x,A,B,F,K);Q=E(ca);var va=P(ca);if(va==null)return a.La?a.La(b,c,d,e,h,g,k,l,m,n,p,q,r,x,A,B,F,K,Q):a.call(a,b,c,d,e,h,g,k,l,m,n,p,q,r,x,A,B,F,K,Q);ca=E(va);va=P(va);if(va==null)return a.Ma?a.Ma(b,c,d,e,h,g,k,l,m,n,p,q,r,x,A,B,F,K,Q,ca):a.call(a,b,c,d,e,h,g,k,l,m,n,p,q,r,x,A,B,F,K,Q,ca);b=[b,c,d,e,h,g,k,l,m,n,p,q,r,x,A,B,F,K,Q,ca];for(c=va;;)if(c)b.push(E(c)),c=P(c);else break;return a.apply(a,b)}
function fc(a){switch(arguments.length){case 2:return Vc(arguments[0],arguments[1]);case 3:return Wc(arguments[0],arguments[1],arguments[2]);case 4:var b=arguments[0];var c=arguments[1],d=arguments[2],e=arguments[3];b.ba?(c=W(c,W(d,e)),d=b.ga,e=2+Nc(d-1,e),b=e<=d?Pc(b,e,c):b.ba(c)):b=Sc(b,c,d,J(e));return b;case 5:b=arguments[0];c=arguments[1];d=arguments[2];var g=arguments[3];e=arguments[4];b.ba?(c=W(c,W(d,W(g,e))),d=b.ga,e=3+Nc(d-2,e),b=e<=d?Pc(b,e,c):b.ba(c)):b=Tc(b,c,d,g,J(e));return b;default:e=
[];b=arguments.length;for(c=0;;)if(c<b)e.push(arguments[c]),c+=1;else break;b=arguments[0];c=arguments[1];d=arguments[2];g=arguments[3];var h=arguments[4];e=5<e.length?new M(e.slice(5),0,null):null;b.ba?(e=Oc(e),c=W(c,W(d,W(g,W(h,e)))),d=b.ga,e=4+Nc(d-3,e),b=e<=d?Pc(b,e,c):b.ba(c)):b=Uc(b,c,d,g,h,Oc(e));return b}}function Vc(a,b){if(a.ba){var c=a.ga,d=Nc(c+1,b);return d<=c?Pc(a,d,b):a.ba(b)}b=J(b);return b==null?a.F?a.F():a.call(a):Rc(a,E(b),Qc(b))}
function Wc(a,b,c){if(a.ba){b=W(b,c);var d=a.ga;c=Nc(d,c)+1;return c<=d?Pc(a,c,b):a.ba(b)}return Rc(a,b,J(c))}function Xc(a){this.Lb=a;this.j=393216;this.A=0}f=Xc.prototype;f.O=function(a,b){return new Xc(b)};f.N=function(){return this.Lb};f.ia=function(){return!1};f.next=function(){return Error("No such element")};f.remove=function(){return Error("Unsupported operation")};function Yc(a,b){for(;;){if(J(b)==null)return!0;var c=N(b);c=a.g?a.g(c):a.call(null,c);if(v(c))b=P(b);else return!1}}
var X=function X(a){switch(arguments.length){case 1:return X.g(arguments[0]);case 2:return X.h(arguments[0],arguments[1]);case 3:return X.m(arguments[0],arguments[1],arguments[2]);case 4:return X.ea(arguments[0],arguments[1],arguments[2],arguments[3]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return X.R(arguments[0],arguments[1],arguments[2],arguments[3],4<c.length?new M(c.slice(4),0,null):null)}};
X.g=function(a){return function(b){return function(){function c(k,l){l=a.g?a.g(l):a.call(null,l);return b.h?b.h(k,l):b.call(null,k,l)}function d(k){return b.g?b.g(k):b.call(null,k)}function e(){return b.F?b.F():b.call(null)}var g=null,h=function(){function k(m,n,p){var q=null;if(arguments.length>2){q=0;for(var r=Array(arguments.length-2);q<r.length;)r[q]=arguments[q+2],++q;q=new M(r,0,null)}return l.call(this,m,n,q)}function l(m,n,p){n=Wc(a,n,p);return b.h?b.h(m,n):b.call(null,m,n)}k.ga=2;k.ba=function(m){var n=
N(m);m=P(m);var p=N(m);m=Db(m);return l(n,p,m)};k.R=l;return k}();g=function(k,l,m){switch(arguments.length){case 0:return e.call(this);case 1:return d.call(this,k);case 2:return c.call(this,k,l);default:var n=null;if(arguments.length>2){n=0;for(var p=Array(arguments.length-2);n<p.length;)p[n]=arguments[n+2],++n;n=new M(p,0,null)}return h.R(k,l,n)}throw Error("Invalid arity: "+arguments.length);};g.ga=2;g.ba=h.ba;g.F=e;g.g=d;g.h=c;g.R=h.R;return g}()}};
X.h=function(a,b){return new Gc(null,function(){var c=J(b);if(c){if(mc(c)){for(var d=ab(c),e=U(d),g=new Ic(Array(e)),h=0;;)if(h<e)Mc(g,function(){var k=D(d,h);return a.g?a.g(k):a.call(null,k)}()),h+=1;else break;return Lc(g.ta(),X.h(a,bb(c)))}return W(function(){var k=N(c);return a.g?a.g(k):a.call(null,k)}(),X.h(a,Db(c)))}return null},null)};
X.m=function(a,b,c){return new Gc(null,function(){var d=J(b),e=J(c);if(d&&e){var g=N(d);var h=N(e);g=a.h?a.h(g,h):a.call(null,g,h);d=W(g,X.m(a,Db(d),Db(e)))}else d=null;return d},null)};X.ea=function(a,b,c,d){return new Gc(null,function(){var e=J(b),g=J(c),h=J(d);if(e&&g&&h){var k=N(e);var l=N(g),m=N(h);k=a.m?a.m(k,l,m):a.call(null,k,l,m);e=W(k,X.ea(a,Db(e),Db(g),Db(h)))}else e=null;return e},null)};
X.R=function(a,b,c,d,e){return X.h(function(g){return Vc(a,g)},function k(h){return new Gc(null,function(){var l=X.h(J,h);return Yc(yc,l)?W(X.h(N,l),k(X.h(Db,l))):null},null)}(Xb.R(e,d,Wb([c,b]))))};X.ba=function(a){var b=N(a),c=P(a);a=N(c);var d=P(c);c=N(d);var e=P(d);d=N(e);e=P(e);return this.R(b,a,c,d,e)};X.ga=4;function Zc(a,b){if(a!=null)if(a!=null&&(a.A&4||u===a.Pb)){var c=Ha;b=sc(Xa,Wa(a),b);b=Ya(b);a=c(b,hc(a))}else a=sc(oa,a,b);else a=sc(Xb,a,b);return a}
function $c(a,b){this.C=a;this.i=b}function ad(a){return new $c(a,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null])}function bd(a){a=a.l;return a<32?0:a-1>>>5<<5}function cd(a,b,c){for(;;){if(b===0)return c;var d=ad(a);d.i[0]=c;c=d;b-=5}}
var dd=function dd(a,b,c,d){var g=new $c(c.C,C(c.i)),h=a.l-1>>>b&31;5===b?g.i[h]=d:(c=c.i[h],c!=null?(b-=5,a=dd.ea?dd.ea(a,b,c,d):dd.call(null,a,b,c,d)):a=cd(null,b-5,d),g.i[h]=a);return g};function ed(a,b){if(b>=bd(a))return a.da;var c=a.root;for(a=a.shift;;)if(a>0){var d=a-5;c=c.i[b>>>a&31];a=d}else return c.i}function fd(a,b){if(0<=b&&b<a.l)b=ed(a,b);else throw a=a.l,Error(["No item ",z.g(b)," in vector of length ",z.g(a)].join(""));return b}
var gd=function gd(a,b,c,d,e){var h=new $c(c.C,C(c.i));if(b===0)h.i[d&31]=e;else{var k=d>>>b&31;b-=5;c=c.i[k];a=gd.ua?gd.ua(a,b,c,d,e):gd.call(null,a,b,c,d,e);h.i[k]=a}return h};function hd(a,b,c){this.kb=this.o=0;this.i=a;this.Nb=b;this.start=0;this.end=c}hd.prototype.ia=function(){return this.o<this.end};hd.prototype.next=function(){this.o-this.kb===32&&(this.i=ed(this.Nb,this.o),this.kb+=32);var a=this.i[this.o&31];this.o+=1;return a};
function id(a,b,c,d){return c<d?jd(a,b,Sb(a,c),c+1,d):b.F?b.F():b.call(null)}function jd(a,b,c,d,e){var g=c;c=d;for(d=ed(a,d);;)if(c<e){var h=c&31;d=h===0?ed(a,c):d;h=d[h];g=b.h?b.h(g,h):b.call(null,g,h);if(Lb(g))return Ea(g);c+=1}else return g}function Y(a,b,c,d,e,g){this.u=a;this.l=b;this.shift=c;this.root=d;this.da=e;this.v=g;this.j=167666463;this.A=401412}f=Y.prototype;f.toString=function(){return fb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,U(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.ka=function(a,b){return this.H(null,b,null)};f.H=function(a,b,c){return typeof b==="number"?this.la(null,b,c):c};
f.gb=function(a,b,c){a=0;for(var d=c;;)if(a<this.l){var e=ed(this,a);c=e.length;a:{for(var g=0;;)if(g<c){var h=g+a,k=e[g];d=b.m?b.m(d,h,k):b.call(null,d,h,k);if(Lb(d)){e=d;break a}g+=1}else{e=d;break a}e=void 0}if(Lb(e))return Ea(e);a+=c;d=e}else return d};f.X=function(a,b){return fd(this,b)[b&31]};f.la=function(a,b,c){return 0<=b&&b<this.l?ed(this,b)[b&31]:c};
f.ob=function(a,b){if(0<=a&&a<this.l){if(bd(this)<=a){var c=C(this.da);c[a&31]=b;return new Y(this.u,this.l,this.shift,this.root,c,null)}return new Y(this.u,this.l,this.shift,gd(this,this.shift,this.root,a,b),this.da,null)}if(a===this.l)return this.U(null,b);throw Error(["Index ",z.g(a)," out of bounds  [0,",z.g(this.l),"]"].join(""));};f.sa=function(){var a=this.l;return new hd(0<U(this)?ed(this,0):null,this,a)};f.N=function(){return this.u};f.V=function(){return this.l};
f.M=function(){var a=this.v;return a!=null?a:this.v=a=Gb(this)};f.I=function(a,b){if(b instanceof Y)if(this.l===U(b))for(a=this.sa(null),b=b.sa(null);;){if(a.ia()){var c=a.next(),d=b.next();if(R.h(c,d))continue;else return!1}else return!0;break}else return!1;else return Vb(this,b)};f.Xa=function(){return new kd(this.l,this.shift,ld.g?ld.g(this.root):ld.call(null,this.root),md.g?md.g(this.da):md.call(null,this.da))};f.W=function(){return Ha(Yb,this.u)};f.Z=function(a,b){return id(this,b,0,this.l)};
f.$=function(a,b,c){a=0;for(var d=c;;)if(a<this.l){var e=ed(this,a);c=e.length;a:{for(var g=0;;)if(g<c){var h=e[g];d=b.h?b.h(d,h):b.call(null,d,h);if(Lb(d)){e=d;break a}g+=1}else{e=d;break a}e=void 0}if(Lb(e))return Ea(e);a+=c;d=e}else return d};f.xa=function(a,b,c){if(typeof b==="number")return this.ob(b,c);throw Error("Vector's key for assoc must be a number.");};f.Ua=function(a,b){return typeof b!=="number"||isNaN(b)||b===Infinity||parseFloat(b)!==parseInt(b,10)?!1:0<=b&&b<this.l};
f.T=function(){if(this.l===0)return null;if(this.l<=32)return new M(this.da,0,null);a:{var a=this.root;for(var b=this.shift;;)if(b>0)b-=5,a=a.i[0];else{a=a.i;break a}a=void 0}return nd?nd(this,a,0,0):od.call(null,this,a,0,0)};f.O=function(a,b){return b===this.u?this:new Y(b,this.l,this.shift,this.root,this.da,this.v)};
f.U=function(a,b){if(this.l-bd(this)<32){a=this.da.length;for(var c=Array(a+1),d=0;;)if(d<a)c[d]=this.da[d],d+=1;else break;c[a]=b;return new Y(this.u,this.l+1,this.shift,this.root,c,null)}a=(c=this.l>>>5>1<<this.shift)?this.shift+5:this.shift;c?(c=ad(null),c.i[0]=this.root,d=cd(null,this.shift,new $c(null,this.da)),c.i[1]=d):c=dd(this,this.shift,this.root,new $c(null,this.da));return new Y(this.u,this.l+1,a,c,[b],null)};
f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);default:throw Error(["Invalid arity: ",z.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(C(b)))};f.g=function(a){if(typeof a==="number")return this.X(null,a);throw Error("Key must be integer");};
var pd=new $c(null,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]),Yb=new Y(null,0,5,pd,[],Hb);Y.prototype[ja]=function(){return S(this)};function qd(a,b,c,d,e){this.ja=a;this.node=b;this.o=c;this.P=d;this.u=e;this.v=null;this.j=32375020;this.A=263680}f=qd.prototype;f.toString=function(){return fb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,U(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.N=function(){return this.u};f.S=function(){if(this.P+1<this.node.length){var a=this.ja;var b=this.node,c=this.o,d=this.P+1;a=nd?nd(a,b,c,d):od.call(null,a,b,c,d);return a==null?null:a}return this.sb()};
f.M=function(){var a=this.v;return a!=null?a:this.v=a=Gb(this)};f.I=function(a,b){return Vb(this,b)};f.W=function(){return O};f.Z=function(a,b){return id(this.ja,b,this.o+this.P,U(this.ja))};f.$=function(a,b,c){return jd(this.ja,b,c,this.o+this.P,U(this.ja))};f.aa=function(){return this.node[this.P]};f.fa=function(){if(this.P+1<this.node.length){var a=this.ja;var b=this.node,c=this.o,d=this.P+1;a=nd?nd(a,b,c,d):od.call(null,a,b,c,d);return a==null?O:a}return this.fb(null)};f.T=function(){return this};
f.mb=function(){var a=this.node;return new Jc(a,this.P,a.length)};f.fb=function(){var a=this.o+this.node.length;if(a<la(this.ja)){var b=this.ja,c=ed(this.ja,a);return nd?nd(b,c,a,0):od.call(null,b,c,a,0)}return O};f.O=function(a,b){return b===this.u?this:rd?rd(this.ja,this.node,this.o,this.P,b):od.call(null,this.ja,this.node,this.o,this.P,b)};f.U=function(a,b){return W(b,this)};
f.sb=function(){var a=this.o+this.node.length;if(a<la(this.ja)){var b=this.ja,c=ed(this.ja,a);return nd?nd(b,c,a,0):od.call(null,b,c,a,0)}return null};qd.prototype[ja]=function(){return S(this)};
function od(a){switch(arguments.length){case 3:var b=arguments[0],c=arguments[1],d=arguments[2];return new qd(b,fd(b,c),c,d,null);case 4:return nd(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return rd(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);default:throw Error(["Invalid arity: ",z.g(arguments.length)].join(""));}}function nd(a,b,c,d){return new qd(a,b,c,d,null)}function rd(a,b,c,d,e){return new qd(a,b,c,d,e)}
function sd(a,b){return a===b.C?b:new $c(a,C(b.i))}function ld(a){return new $c({},C(a.i))}function md(a){var b=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];nc(a,0,b,0,a.length);return b}var td=function td(a,b,c,d){c=sd(a.root.C,c);var g=a.l-1>>>b&31;if(b===5)a=d;else{var h=c.i[g];h!=null?(b-=5,a=td.ea?td.ea(a,b,h,d):td.call(null,a,b,h,d)):a=cd(a.root.C,b-5,d)}c.i[g]=a;return c};
function kd(a,b,c,d){this.l=a;this.shift=b;this.root=c;this.da=d;this.A=88;this.j=275}f=kd.prototype;
f.Za=function(a,b){if(this.root.C){if(this.l-bd(this)<32)this.da[this.l&31]=b;else{a=new $c(this.root.C,this.da);var c=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];c[0]=b;this.da=c;this.l>>>5>1<<this.shift?(b=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],c=this.shift+
5,b[0]=this.root,b[1]=cd(this.root.C,this.shift,a),this.root=new $c(this.root.C,b),this.shift=c):this.root=td(this,this.shift,this.root,a)}this.l+=1;return this}throw Error("conj! after persistent!");};f.ib=function(){if(this.root.C){this.root.C=null;var a=this.l-bd(this),b=Array(a);nc(this.da,0,b,0,a);return new Y(null,this.l,this.shift,this.root,b,null)}throw Error("persistent! called twice");};
f.Va=function(a,b,c){if(typeof b==="number")return ud(this,b,c);throw Error("TransientVector's key for assoc! must be a number.");};
function ud(a,b,c){if(a.root.C){if(0<=b&&b<a.l){if(bd(a)<=b)a.da[b&31]=c;else{var d=function k(g,h){h=sd(a.root.C,h);if(g===0)h.i[b&31]=c;else{var l=b>>>g&31;g=k(g-5,h.i[l]);h.i[l]=g}return h}(a.shift,a.root);a.root=d}return a}if(b===a.l)return a.Za(null,c);throw Error(["Index ",z.g(b)," out of bounds for TransientVector of length",z.g(a.l)].join(""));}throw Error("assoc! after persistent!");}f.V=function(){if(this.root.C)return this.l;throw Error("count after persistent!");};
f.X=function(a,b){if(this.root.C)return fd(this,b)[b&31];throw Error("nth after persistent!");};f.la=function(a,b,c){return 0<=b&&b<this.l?this.X(null,b):c};f.ka=function(a,b){return this.H(null,b,null)};f.H=function(a,b,c){if(this.root.C)return typeof b==="number"?this.la(null,b,c):c;throw Error("lookup after persistent!");};
f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(C(b)))};f.g=function(a){return this.ka(null,a)};f.h=function(a,b){return this.H(null,a,b)};function vd(){this.j=2097152;this.A=0}vd.prototype.I=function(){return!1};var wd=new vd;
function xd(a,b){return pc(jc(b)&&!kc(b)?U(a)===U(b)?(a!=null?a.j&1048576||u===a.Cb||(a.j?0:w(La,a)):w(La,a))?xc(function(c,d,e){return R.h(zb(b,d,wd),e)?!0:new Kb},a):Yc(function(c){return R.h(zb(b,N(c),wd),N(P(c)))},a):null:null)}function yd(a){this.D=a}yd.prototype.next=function(){if(this.D!=null){var a=N(this.D),b=ac(a,0,null);a=ac(a,1,null);this.D=P(this.D);return{value:[b,a],done:!1}}return{value:null,done:!0}};function zd(a){return new yd(J(a))}
function Ad(a,b){if(b instanceof I)a:{var c=a.length;b=b.va;for(var d=0;;){if(c<=d){a=-1;break a}if(a[d]instanceof I&&b===a[d].va){a=d;break a}d+=2}a=void 0}else if(typeof b==="string"||typeof b==="number")a:{c=a.length;for(d=0;;){if(c<=d){a=-1;break a}if(b===a[d]){a=d;break a}d+=2}a=void 0}else if(b instanceof wb)a:{c=a.length;b=b.Aa;for(d=0;;){if(c<=d){a=-1;break a}if(a[d]instanceof wb&&b===a[d].Aa){a=d;break a}d+=2}a=void 0}else if(b==null)a:{b=a.length;for(c=0;;){if(b<=c){a=-1;break a}if(a[c]==
null){a=c;break a}c+=2}a=void 0}else a:{c=a.length;for(d=0;;){if(c<=d){a=-1;break a}if(R.h(b,a[d])){a=d;break a}d+=2}a=void 0}return a}function Bd(a,b){this.key=a;this.G=b;this.v=null;this.j=166619935;this.A=0}f=Bd.prototype;f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,U(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.ka=function(a,b){return this.la(null,b,null)};f.H=function(a,b,c){return this.la(null,b,c)};f.X=function(a,b){if(b===0)return this.key;if(b===1)return this.G;throw Error("Index out of bounds");};
f.la=function(a,b,c){return b===0?this.key:b===1?this.G:c};f.ob=function(a,b){return(new Y(null,2,5,pd,[this.key,this.G],null)).ob(a,b)};f.N=function(){return null};f.V=function(){return 2};f.Eb=function(){return this.key};f.Fb=function(){return this.G};f.M=function(){var a=this.v;return a!=null?a:this.v=a=Gb(this)};f.I=function(a,b){return Vb(this,b)};f.W=function(){return null};
f.Z=function(a,b){a:if(a=this.V(null),a===0)b=b.F?b.F():b.call(null);else{for(var c=this.X(null,0),d=1;;)if(d<a){var e=this.X(null,d);c=b.h?b.h(c,e):b.call(null,c,e);if(Lb(c)){b=Ea(c);break a}d+=1}else{b=c;break a}b=void 0}return b};f.$=function(a,b,c){a:{a=this.V(null);var d=c;for(c=0;;)if(c<a){var e=this.X(null,c);d=b.h?b.h(d,e):b.call(null,d,e);if(Lb(d)){b=Ea(d);break a}c+=1}else{b=d;break a}b=void 0}return b};f.xa=function(a,b,c){return bc.m(new Y(null,2,5,pd,[this.key,this.G],null),b,c)};
f.Ua=function(a,b){return b===0||b===1};f.T=function(){return new M([this.key,this.G],0,null)};f.O=function(a,b){return gc(new Y(null,2,5,pd,[this.key,this.G],null),b)};f.U=function(a,b){return new Y(null,3,5,pd,[this.key,this.G,b],null)};f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(C(b)))};
f.g=function(a){return this.X(null,a)};f.h=function(a,b){return this.la(null,a,b)};function Cd(a){return a!=null?a.j&2048||u===a.Ub?!0:!1:!1}function Dd(a,b,c){this.i=a;this.o=b;this.ra=c;this.j=32374990;this.A=262144}f=Dd.prototype;f.toString=function(){return fb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,U(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.N=function(){return this.ra};f.S=function(){return this.o<this.i.length-2?new Dd(this.i,this.o+2,null):null};f.V=function(){return(this.i.length-this.o)/2};f.M=function(){return Gb(this)};f.I=function(a,b){return Vb(this,b)};
f.W=function(){return O};f.Z=function(a,b){return rc(b,this)};f.$=function(a,b,c){return uc(b,c,this)};f.aa=function(){return new Bd(this.i[this.o],this.i[this.o+1])};f.fa=function(){return this.o<this.i.length-2?new Dd(this.i,this.o+2,null):O};f.T=function(){return this};f.O=function(a,b){return b===this.ra?this:new Dd(this.i,this.o,b)};f.U=function(a,b){return W(b,this)};Dd.prototype[ja]=function(){return S(this)};function Ed(a,b){this.i=a;this.o=0;this.l=b}
Ed.prototype.ia=function(){return this.o<this.l};Ed.prototype.next=function(){var a=new Bd(this.i[this.o],this.i[this.o+1]);this.o+=2;return a};function gb(a,b,c,d){this.u=a;this.l=b;this.i=c;this.v=d;this.j=16647951;this.A=401412}f=gb.prototype;f.toString=function(){return fb(this)};f.keys=function(){return S(Fd.g?Fd.g(this):Fd.call(null,this))};f.entries=function(){return zd(J(this))};f.values=function(){return S(Gd.g?Gd.g(this):Gd.call(null,this))};f.has=function(a){return qc(this,a)};
f.get=function(a,b){return this.H(null,a,b)};f.forEach=function(a){for(var b=J(this),c=null,d=0,e=0;;)if(e<d){var g=c.X(null,e),h=ac(g,0,null);g=ac(g,1,null);a.h?a.h(g,h):a.call(null,g,h);e+=1}else if(b=J(b))mc(b)?(c=ab(b),b=bb(b),h=c,d=U(c),c=h):(c=N(b),h=ac(c,0,null),g=ac(c,1,null),a.h?a.h(g,h):a.call(null,g,h),b=P(b),c=null,d=0),e=0;else return null};f.ka=function(a,b){return this.H(null,b,null)};f.H=function(a,b,c){a=Ad(this.i,b);return a===-1?c:this.i[a+1]};
f.gb=function(a,b,c){a=this.i.length;for(var d=0;;)if(d<a){var e=this.i[d],g=this.i[d+1];c=b.m?b.m(c,e,g):b.call(null,c,e,g);if(Lb(c))return Ea(c);d+=2}else return c};f.sa=function(){return new Ed(this.i,this.l*2)};f.N=function(){return this.u};f.V=function(){return this.l};f.M=function(){var a=this.v;return a!=null?a:this.v=a=Ib(this)};
f.I=function(a,b){if(jc(b)&&!kc(b))if(a=this.i.length,this.l===b.V(null))for(var c=0;;){if(c<a){var d=b.H(null,this.i[c],oc);if(d!==oc)if(R.h(this.i[c+1],d)){c+=2;continue}else return!1;else return!1}else return!0;break}else return!1;else return!1};f.Xa=function(){return new Hd(this.i.length,C(this.i))};f.W=function(){return Ha(Id,this.u)};f.Z=function(a,b){return vc(this,b)};f.$=function(a,b,c){return wc(this,b,c)};
f.xa=function(a,b,c){a=Ad(this.i,b);if(a===-1){if(this.l<Jd){a=this.i;for(var d=a.length,e=Array(d+2),g=0;;)if(g<d)e[g]=a[g],g+=1;else break;e[d]=b;e[d+1]=c;return new gb(this.u,this.l+1,e,null)}return Ha(za(Zc(Kd,this),b,c),this.u)}if(c===this.i[a+1])return this;b=C(this.i);b[a+1]=c;return new gb(this.u,this.l,b,null)};f.Ua=function(a,b){return Ad(this.i,b)!==-1};f.T=function(){var a=this.i;return 0<=a.length-2?new Dd(a,0,null):null};
f.O=function(a,b){return b===this.u?this:new gb(b,this.l,this.i,this.v)};f.U=function(a,b){if(lc(b))return this.xa(null,D(b,0),D(b,1));a=this;for(b=J(b);;){if(b==null)return a;var c=N(b);if(lc(c))a=za(a,D(c,0),D(c,1)),b=P(b);else throw Error("conj on a map takes map entries or seqables of map entries");}};
f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(C(b)))};f.g=function(a){return this.ka(null,a)};f.h=function(a,b){return this.H(null,a,b)};var Id=new gb(null,0,[],Jb),Jd=8;function cc(a,b){return a===b?!0:a===b||a instanceof I&&b instanceof I&&a.va===b.va?!0:R.h(a,b)}
function Md(a){for(var b=0,c=0;;)if(b<a.length){var d;a:{for(d=0;;)if(d<b){var e=cc(a[b],a[d]);if(e){d=e;break a}d=2+d}else{d=!1;break a}d=void 0}c=d?c:c+2;b=2+b}else return c}function Nd(a,b){var c=a.length-1;b=J(b);var d=Array(c+2*U(b));for(a=nc(a,0,d,0,c);;)if(b)d=N(b),a[c]=Ba(d),a[c+1]=Ca(d),c=2+c,b=P(b);else return a}
function dc(a,b){var c=b?Nd(a,Zc(Id,a[a.length-1])):a;a=Md(c);var d=c.length;if(a<d){a=Array(a);for(var e=0,g=0;;)if(e<d)(function(){for(var h=0;;)if(h<g){var k=cc(c[e],c[h]);if(k)return k;h=2+h}else return!1})()?(b=g,e=2+e,g=b):(b=function(){for(var h=d-2;;)if(h>=e){if(cc(c[e],c[h]))return h;h-=2}else return h}(),a[g]=c[e],a[g+1]=c[b+1],b=2+g,e=2+e,g=b);else break;return new gb(null,a.length/2,a,null)}return new gb(null,c.length/2,c,null)}gb.prototype[ja]=function(){return S(this)};
function Hd(a,b){this.Wa={};this.Sa=a;this.i=b;this.j=259;this.A=56}f=Hd.prototype;f.V=function(){if(this.Wa)return zc(this.Sa);throw Error("count after persistent!");};f.ka=function(a,b){return this.H(null,b,null)};f.H=function(a,b,c){if(this.Wa)return a=Ad(this.i,b),a===-1?c:this.i[a+1];throw Error("lookup after persistent!");};
f.Za=function(a,b){if(this.Wa){if(Cd(b))return this.Va(null,Od.g?Od.g(b):Od.call(null,b),Pd.g?Pd.g(b):Pd.call(null,b));if(lc(b))return this.Va(null,b.g?b.g(0):b.call(null,0),b.g?b.g(1):b.call(null,1));a=J(b);for(b=this;;){var c=N(a);if(v(c))a=P(a),b=Za(b,Od.g?Od.g(c):Od.call(null,c),Pd.g?Pd.g(c):Pd.call(null,c));else return b}}else throw Error("conj! after persistent!");};f.ib=function(){if(this.Wa)return this.Wa=!1,new gb(null,zc(this.Sa),this.i,null);throw Error("persistent! called twice");};
f.Va=function(a,b,c){if(this.Wa){a=Ad(this.i,b);if(a===-1){if(this.Sa+2<=2*Jd)return this.Sa+=2,this.i.push(b),this.i.push(c),this;a=Qd.h?Qd.h(this.Sa,this.i):Qd.call(null,this.Sa,this.i);return Za(a,b,c)}c!==this.i[a+1]&&(this.i[a+1]=c);return this}throw Error("assoc! after persistent!");};f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length-1)].join(""));}};
f.apply=function(a,b){return this.call.apply(this,[this].concat(C(b)))};f.g=function(a){return this.H(null,a,null)};f.h=function(a,b){return this.H(null,a,b)};function Qd(a,b){for(var c=Wa(Kd),d=0;;)if(d<a)c=Za(c,b[d],b[d+1]),d+=2;else return c}function Rd(){this.G=!1}function Sd(a,b,c){a=C(a);a[b]=c;return a}function Td(a,b,c,d){a=a.Ra(b);a.i[c]=d;return a}
function Ud(a,b,c){for(var d=a.length,e=0,g=c;;)if(e<d){c=a[e];if(c!=null){var h=a[e+1];c=b.m?b.m(g,c,h):b.call(null,g,c,h)}else c=a[e+1],c=c!=null?c.bb(b,g):g;if(Lb(c))return c;e+=2;g=c}else return g}function Vd(a){this.i=a;this.o=0;this.pa=this.cb=null}Vd.prototype.advance=function(){for(var a=this.i.length;;)if(this.o<a){var b=this.i[this.o],c=this.i[this.o+1];b!=null?b=this.cb=new Bd(b,c):c!=null?(b=db(c),b=b.ia()?this.pa=b:!1):b=!1;this.o+=2;if(b)return!0}else return!1};
Vd.prototype.ia=function(){var a=this.cb!=null;return a?a:(a=this.pa!=null)?a:this.advance()};Vd.prototype.next=function(){if(this.cb!=null){var a=this.cb;this.cb=null;return a}if(this.pa!=null)return a=this.pa.next(),this.pa.ia()||(this.pa=null),a;if(this.advance())return this.next();throw Error("No such element");};Vd.prototype.remove=function(){return Error("Unsupported operation")};function Wd(a,b,c){this.C=a;this.K=b;this.i=c;this.A=131072;this.j=0}f=Wd.prototype;
f.Ra=function(a){if(a===this.C)return this;var b=Ac(this.K),c=Array(b<0?4:2*(b+1));nc(this.i,0,c,0,2*b);return new Wd(a,this.K,c)};f.ab=function(){return Xd?Xd(this.i):Yd.call(null,this.i)};f.bb=function(a,b){return Ud(this.i,a,b)};f.za=function(a,b,c,d){var e=1<<(b>>>a&31);if((this.K&e)===0)return d;var g=Ac(this.K&e-1);e=this.i[2*g];g=this.i[2*g+1];return e==null?g.za(a+5,b,c,d):cc(c,e)?g:d};
f.na=function(a,b,c,d,e,g){var h=1<<(c>>>b&31),k=Ac(this.K&h-1);if((this.K&h)===0){var l=Ac(this.K);if(2*l<this.i.length){a=this.Ra(a);b=a.i;g.G=!0;c=2*(l-k);g=2*k+(c-1);for(l=2*(k+1)+(c-1);c!==0;)b[l]=b[g],--l,--c,--g;b[2*k]=d;b[2*k+1]=e;a.K|=h;return a}if(l>=16){k=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];k[c>>>b&31]=Zd.na(a,b+5,c,d,e,g);for(e=d=0;;)if(d<32)(this.K>>>d&1)===0?
d+=1:(k[d]=this.i[e]!=null?Zd.na(a,b+5,ub(this.i[e]),this.i[e],this.i[e+1],g):this.i[e+1],e+=2,d+=1);else break;return new $d(a,l+1,k)}b=Array(2*(l+4));nc(this.i,0,b,0,2*k);b[2*k]=d;b[2*k+1]=e;nc(this.i,2*k,b,2*(k+1),2*(l-k));g.G=!0;a=this.Ra(a);a.i=b;a.K|=h;return a}l=this.i[2*k];h=this.i[2*k+1];if(l==null)return l=h.na(a,b+5,c,d,e,g),l===h?this:Td(this,a,2*k+1,l);if(cc(d,l))return e===h?this:Td(this,a,2*k+1,e);g.G=!0;g=b+5;d=ae?ae(a,g,l,h,c,d,e):be.call(null,a,g,l,h,c,d,e);e=2*k;k=2*k+1;a=this.Ra(a);
a.i[e]=null;a.i[k]=d;return a};
f.ma=function(a,b,c,d,e){var g=1<<(b>>>a&31),h=Ac(this.K&g-1);if((this.K&g)===0){var k=Ac(this.K);if(k>=16){h=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];h[b>>>a&31]=Zd.ma(a+5,b,c,d,e);for(d=c=0;;)if(c<32)(this.K>>>c&1)===0?c+=1:(h[c]=this.i[d]!=null?Zd.ma(a+5,ub(this.i[d]),this.i[d],this.i[d+1],e):this.i[d+1],d+=2,c+=1);else break;return new $d(null,k+1,h)}a=Array(2*(k+1));nc(this.i,
0,a,0,2*h);a[2*h]=c;a[2*h+1]=d;nc(this.i,2*h,a,2*(h+1),2*(k-h));e.G=!0;return new Wd(null,this.K|g,a)}var l=this.i[2*h];g=this.i[2*h+1];if(l==null)return k=g.ma(a+5,b,c,d,e),k===g?this:new Wd(null,this.K,Sd(this.i,2*h+1,k));if(cc(c,l))return d===g?this:new Wd(null,this.K,Sd(this.i,2*h+1,d));e.G=!0;e=this.K;k=this.i;a+=5;a=ce?ce(a,l,g,b,c,d):be.call(null,a,l,g,b,c,d);c=2*h;h=2*h+1;d=C(k);d[c]=null;d[h]=a;return new Wd(null,e,d)};f.sa=function(){return new Vd(this.i)};var Zd=new Wd(null,0,[]);
function de(a){this.i=a;this.o=0;this.pa=null}de.prototype.ia=function(){for(var a=this.i.length;;){if(this.pa!=null&&this.pa.ia())return!0;if(this.o<a){var b=this.i[this.o];this.o+=1;b!=null&&(this.pa=db(b))}else return!1}};de.prototype.next=function(){if(this.ia())return this.pa.next();throw Error("No such element");};de.prototype.remove=function(){return Error("Unsupported operation")};function $d(a,b,c){this.C=a;this.l=b;this.i=c;this.A=131072;this.j=0}f=$d.prototype;
f.Ra=function(a){return a===this.C?this:new $d(a,this.l,C(this.i))};f.ab=function(){return ee?ee(this.i):fe.call(null,this.i)};f.bb=function(a,b){for(var c=this.i.length,d=0;;)if(d<c){var e=this.i[d];if(e!=null){b=e.bb(a,b);if(Lb(b))return b;d+=1}else d+=1}else return b};f.za=function(a,b,c,d){var e=this.i[b>>>a&31];return e!=null?e.za(a+5,b,c,d):d};
f.na=function(a,b,c,d,e,g){var h=c>>>b&31,k=this.i[h];if(k==null)return a=Td(this,a,h,Zd.na(a,b+5,c,d,e,g)),a.l+=1,a;b=k.na(a,b+5,c,d,e,g);return b===k?this:Td(this,a,h,b)};f.ma=function(a,b,c,d,e){var g=b>>>a&31,h=this.i[g];if(h==null)return new $d(null,this.l+1,Sd(this.i,g,Zd.ma(a+5,b,c,d,e)));a=h.ma(a+5,b,c,d,e);return a===h?this:new $d(null,this.l,Sd(this.i,g,a))};f.sa=function(){return new de(this.i)};function ge(a,b,c){b*=2;for(var d=0;;)if(d<b){if(cc(c,a[d]))return d;d+=2}else return-1}
function he(a,b,c,d){this.C=a;this.ya=b;this.l=c;this.i=d;this.A=131072;this.j=0}f=he.prototype;f.Ra=function(a){if(a===this.C)return this;var b=Array(2*(this.l+1));nc(this.i,0,b,0,2*this.l);return new he(a,this.ya,this.l,b)};f.ab=function(){return Xd?Xd(this.i):Yd.call(null,this.i)};f.bb=function(a,b){return Ud(this.i,a,b)};f.za=function(a,b,c,d){a=ge(this.i,this.l,c);return a<0?d:this.i[a+1]};
f.na=function(a,b,c,d,e,g){if(c===this.ya){b=ge(this.i,this.l,d);if(b===-1){if(this.i.length>2*this.l)return b=2*this.l,c=2*this.l+1,a=this.Ra(a),a.i[b]=d,a.i[c]=e,g.G=!0,a.l+=1,a;c=this.i.length;b=Array(c+2);nc(this.i,0,b,0,c);b[c]=d;b[c+1]=e;g.G=!0;d=this.l+1;a===this.C?(this.i=b,this.l=d,a=this):a=new he(this.C,this.ya,d,b);return a}return this.i[b+1]===e?this:Td(this,a,b+1,e)}return(new Wd(a,1<<(this.ya>>>b&31),[null,this,null,null])).na(a,b,c,d,e,g)};
f.ma=function(a,b,c,d,e){return b===this.ya?(a=ge(this.i,this.l,c),a===-1?(a=2*this.l,b=Array(a+2),nc(this.i,0,b,0,a),b[a]=c,b[a+1]=d,e.G=!0,new he(null,this.ya,this.l+1,b)):R.h(this.i[a+1],d)?this:new he(null,this.ya,this.l,Sd(this.i,a+1,d))):(new Wd(null,1<<(this.ya>>>a&31),[null,this])).ma(a,b,c,d,e)};f.sa=function(){return new Vd(this.i)};
function be(a){switch(arguments.length){case 6:return ce(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);case 7:return ae(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6]);default:throw Error(["Invalid arity: ",z.g(arguments.length)].join(""));}}function ce(a,b,c,d,e,g){var h=ub(b);if(h===d)return new he(null,h,2,[b,c,e,g]);var k=new Rd;return Zd.ma(a,h,b,c,k).ma(a,d,e,g,k)}
function ae(a,b,c,d,e,g,h){var k=ub(c);if(k===e)return new he(null,k,2,[c,d,g,h]);var l=new Rd;return Zd.na(a,b,k,c,d,l).na(a,b,e,g,h,l)}function ie(a,b,c,d,e){this.u=a;this.qa=b;this.o=c;this.D=d;this.v=e;this.j=32374988;this.A=0}f=ie.prototype;f.toString=function(){return fb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,U(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.N=function(){return this.u};f.S=function(){if(this.D==null){var a=this.qa,b=this.o+2;return je?je(a,b,null):Yd.call(null,a,b,null)}a=this.qa;b=this.o;var c=P(this.D);return je?je(a,b,c):Yd.call(null,a,b,c)};
f.M=function(){var a=this.v;return a!=null?a:this.v=a=Gb(this)};f.I=function(a,b){return Vb(this,b)};f.W=function(){return O};f.Z=function(a,b){return rc(b,this)};f.$=function(a,b,c){return uc(b,c,this)};f.aa=function(){return this.D==null?new Bd(this.qa[this.o],this.qa[this.o+1]):N(this.D)};
f.fa=function(){var a=this,b=a.D==null?function(){var c=a.qa,d=a.o+2;return je?je(c,d,null):Yd.call(null,c,d,null)}():function(){var c=a.qa,d=a.o,e=P(a.D);return je?je(c,d,e):Yd.call(null,c,d,e)}();return b!=null?b:O};f.T=function(){return this};f.O=function(a,b){return b===this.u?this:new ie(b,this.qa,this.o,this.D,this.v)};f.U=function(a,b){return W(b,this)};ie.prototype[ja]=function(){return S(this)};
function Yd(a){switch(arguments.length){case 1:return Xd(arguments[0]);case 3:return je(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length)].join(""));}}function Xd(a){return je(a,0,null)}function je(a,b,c){if(c==null)for(c=a.length;;)if(b<c){if(a[b]!=null)return new ie(null,a,b,null,null);var d=a[b+1];if(v(d)&&(d=d.ab(),v(d)))return new ie(null,a,b+2,d,null);b+=2}else return null;else return new ie(null,a,b,c,null)}
function ke(a,b,c,d,e){this.u=a;this.qa=b;this.o=c;this.D=d;this.v=e;this.j=32374988;this.A=0}f=ke.prototype;f.toString=function(){return fb(this)};f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,U(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.N=function(){return this.u};f.S=function(){var a=this.qa,b=this.o,c=P(this.D);return le?le(a,b,c):fe.call(null,a,b,c)};f.M=function(){var a=this.v;return a!=null?a:this.v=a=Gb(this)};f.I=function(a,b){return Vb(this,b)};
f.W=function(){return O};f.Z=function(a,b){return rc(b,this)};f.$=function(a,b,c){return uc(b,c,this)};f.aa=function(){return N(this.D)};f.fa=function(){var a=this.qa;var b=this.o,c=P(this.D);a=le?le(a,b,c):fe.call(null,a,b,c);return a!=null?a:O};f.T=function(){return this};f.O=function(a,b){return b===this.u?this:new ke(b,this.qa,this.o,this.D,this.v)};f.U=function(a,b){return W(b,this)};ke.prototype[ja]=function(){return S(this)};
function fe(a){switch(arguments.length){case 1:return ee(arguments[0]);case 3:return le(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length)].join(""));}}function ee(a){return le(a,0,null)}function le(a,b,c){if(c==null)for(c=a.length;;)if(b<c){var d=a[b];if(v(d)&&(d=d.ab(),v(d)))return new ke(null,a,b+1,d,null);b+=1}else return null;else return new ke(null,a,b,c,null)}function me(a,b){this.ca=a;this.xb=b;this.qb=!1}
me.prototype.ia=function(){return!this.qb||this.xb.ia()};me.prototype.next=function(){if(this.qb)return this.xb.next();this.qb=!0;return new Bd(null,this.ca)};me.prototype.remove=function(){return Error("Unsupported operation")};function ne(a,b,c,d,e,g){this.u=a;this.l=b;this.root=c;this.ha=d;this.ca=e;this.v=g;this.j=16123663;this.A=139268}f=ne.prototype;f.toString=function(){return fb(this)};f.keys=function(){return S(Fd.g?Fd.g(this):Fd.call(null,this))};f.entries=function(){return zd(J(this))};
f.values=function(){return S(Gd.g?Gd.g(this):Gd.call(null,this))};f.has=function(a){return qc(this,a)};f.get=function(a,b){return this.H(null,a,b)};f.forEach=function(a){for(var b=J(this),c=null,d=0,e=0;;)if(e<d){var g=c.X(null,e),h=ac(g,0,null);g=ac(g,1,null);a.h?a.h(g,h):a.call(null,g,h);e+=1}else if(b=J(b))mc(b)?(c=ab(b),b=bb(b),h=c,d=U(c),c=h):(c=N(b),h=ac(c,0,null),g=ac(c,1,null),a.h?a.h(g,h):a.call(null,g,h),b=P(b),c=null,d=0),e=0;else return null};f.ka=function(a,b){return this.H(null,b,null)};
f.H=function(a,b,c){return b==null?this.ha?this.ca:c:this.root==null?c:this.root.za(0,ub(b),b,c)};f.gb=function(a,b,c){a=this.ha?b.m?b.m(c,null,this.ca):b.call(null,c,null,this.ca):c;Lb(a)?b=Ea(a):this.root!=null?(b=this.root.bb(b,a),b=Lb(b)?Mb.g?Mb.g(b):Mb.call(null,b):b):b=a;return b};f.sa=function(){var a=this.root?db(this.root):new Xc(Id);return this.ha?new me(this.ca,a):a};f.N=function(){return this.u};f.V=function(){return this.l};f.M=function(){var a=this.v;return a!=null?a:this.v=a=Ib(this)};
f.I=function(a,b){return xd(this,b)};f.Xa=function(){return new oe(this.root,this.l,this.ha,this.ca)};f.W=function(){return Ha(Kd,this.u)};f.xa=function(a,b,c){if(b==null)return this.ha&&c===this.ca?this:new ne(this.u,this.ha?this.l:this.l+1,this.root,!0,c,null);a=new Rd;b=(this.root==null?Zd:this.root).ma(0,ub(b),b,c,a);return b===this.root?this:new ne(this.u,a.G?this.l+1:this.l,b,this.ha,this.ca,null)};f.Ua=function(a,b){return b==null?this.ha:this.root==null?!1:this.root.za(0,ub(b),b,oc)!==oc};
f.T=function(){if(this.l>0){var a=this.root!=null?this.root.ab():null;return this.ha?W(new Bd(null,this.ca),a):a}return null};f.O=function(a,b){return b===this.u?this:new ne(b,this.l,this.root,this.ha,this.ca,this.v)};f.U=function(a,b){if(lc(b))return this.xa(null,D(b,0),D(b,1));a=this;for(b=J(b);;){if(b==null)return a;var c=N(b);if(lc(c))a=za(a,D(c,0),D(c,1)),b=P(b);else throw Error("conj on a map takes map entries or seqables of map entries");}};
f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(C(b)))};f.g=function(a){return this.ka(null,a)};f.h=function(a,b){return this.H(null,a,b)};var Kd=new ne(null,0,null,!1,null,Jb);ne.prototype[ja]=function(){return S(this)};
function oe(a,b,c,d){this.C={};this.root=a;this.count=b;this.ha=c;this.ca=d;this.j=259;this.A=56}function pe(a,b,c){if(a.C){if(b==null)a.ca!==c&&(a.ca=c),a.ha||(a.count+=1,a.ha=!0);else{var d=new Rd;b=(a.root==null?Zd:a.root).na(a.C,0,ub(b),b,c,d);b!==a.root&&(a.root=b);d.G&&(a.count+=1)}return a}throw Error("assoc! after persistent!");}f=oe.prototype;f.V=function(){if(this.C)return this.count;throw Error("count after persistent!");};
f.ka=function(a,b){return b==null?this.ha?this.ca:null:this.root==null?null:this.root.za(0,ub(b),b)};f.H=function(a,b,c){return b==null?this.ha?this.ca:c:this.root==null?c:this.root.za(0,ub(b),b,c)};
f.Za=function(a,b){a:{if(this.C){if(Cd(b)){a=pe(this,Od.g?Od.g(b):Od.call(null,b),Pd.g?Pd.g(b):Pd.call(null,b));break a}if(lc(b)){a=pe(this,b.g?b.g(0):b.call(null,0),b.g?b.g(1):b.call(null,1));break a}a=J(b);for(b=this;;){var c=N(a);if(v(c))a=P(a),b=pe(b,Od.g?Od.g(c):Od.call(null,c),Pd.g?Pd.g(c):Pd.call(null,c));else{a=b;break a}}}else throw Error("conj! after persistent");a=void 0}return a};
f.ib=function(){if(this.C){this.C=null;var a=new ne(null,this.count,this.root,this.ha,this.ca,null)}else throw Error("persistent! called twice");return a};f.Va=function(a,b,c){return pe(this,b,c)};f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",z.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(C(b)))};
f.g=function(a){return this.ka(null,a)};f.h=function(a,b){return this.H(null,a,b)};function qe(a,b){this.B=a;this.ra=b;this.j=32374988;this.A=0}f=qe.prototype;f.toString=function(){return fb(this)};f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,U(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.N=function(){return this.ra};f.S=function(){var a=(this.B!=null?this.B.j&128||u===this.B.Ya||(this.B.j?0:w(ra,this.B)):w(ra,this.B))?this.B.S(null):P(this.B);return a==null?null:new qe(a,null)};f.M=function(){return Gb(this)};
f.I=function(a,b){return Vb(this,b)};f.W=function(){return O};f.Z=function(a,b){return rc(b,this)};f.$=function(a,b,c){return uc(b,c,this)};f.aa=function(){return this.B.aa(null).key};f.fa=function(){var a=(this.B!=null?this.B.j&128||u===this.B.Ya||(this.B.j?0:w(ra,this.B)):w(ra,this.B))?this.B.S(null):P(this.B);return a!=null?new qe(a,null):O};f.T=function(){return this};f.O=function(a,b){return b===this.ra?this:new qe(this.B,b)};f.U=function(a,b){return W(b,this)};qe.prototype[ja]=function(){return S(this)};
function Fd(a){return(a=J(a))?new qe(a,null):null}function Od(a){return Ba(a)}function re(a,b){this.B=a;this.ra=b;this.j=32374988;this.A=0}f=re.prototype;f.toString=function(){return fb(this)};f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,U(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.N=function(){return this.ra};f.S=function(){var a=(this.B!=null?this.B.j&128||u===this.B.Ya||(this.B.j?0:w(ra,this.B)):w(ra,this.B))?this.B.S(null):P(this.B);return a==null?null:new re(a,null)};f.M=function(){return Gb(this)};
f.I=function(a,b){return Vb(this,b)};f.W=function(){return O};f.Z=function(a,b){return rc(b,this)};f.$=function(a,b,c){return uc(b,c,this)};f.aa=function(){return this.B.aa(null).G};f.fa=function(){var a=(this.B!=null?this.B.j&128||u===this.B.Ya||(this.B.j?0:w(ra,this.B)):w(ra,this.B))?this.B.S(null):P(this.B);return a!=null?new re(a,null):O};f.T=function(){return this};f.O=function(a,b){return b===this.ra?this:new re(this.B,b)};f.U=function(a,b){return W(b,this)};re.prototype[ja]=function(){return S(this)};
function Gd(a){return(a=J(a))?new re(a,null):null}function Pd(a){return Ca(a)}function Fc(a){if(a!=null&&(a.A&4096||u===a.Hb))return a.name;if(typeof a==="string")return a;throw Error(["Doesn't support name: ",z.g(a)].join(""));}
function se(a,b,c,d,e,g,h){var k=fa;fa=fa==null?null:fa-1;try{if(fa!=null&&fa<0)return H(a,"#");H(a,c);if(lb.g(g)===0)J(h)&&H(a,function(){var r=te.g(g);return v(r)?r:"..."}());else{if(J(h)){var l=N(h);b.m?b.m(l,a,g):b.call(null,l,a,g)}for(var m=P(h),n=lb.g(g)-1;;)if(!m||n!=null&&n===0){J(m)&&n===0&&(H(a,d),H(a,function(){var r=te.g(g);return v(r)?r:"..."}()));break}else{H(a,d);var p=N(m);c=a;h=g;b.m?b.m(p,c,h):b.call(null,p,c,h);var q=P(m);c=n-1;m=q;n=c}}return H(a,e)}finally{fa=k}}
function ue(a,b){b=J(b);for(var c=null,d=0,e=0;;)if(e<d){var g=c.X(null,e);H(a,g);e+=1}else if(b=J(b))c=b,mc(c)?(b=ab(c),d=bb(c),c=b,g=U(b),b=d,d=g):(g=N(c),H(a,g),b=P(c),c=null,d=0),e=0;else return null}var ve={'"':'\\"',"\\":"\\\\","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"};function we(a){return['"',z.g(a.replace(RegExp('[\\\\"\b\f\n\r\t]',"g"),function(b){return ve[b]})),'"'].join("")}
function xe(a,b){return(a=pc(xb(a,jb)))?(a=b!=null?b.j&131072||u===b.Gb?!0:!1:!1)?hc(b)!=null:a:a}
function ye(a,b,c){if(a==null)return H(b,"nil");if(xe(c,a)){H(b,"^");var d=hc(a);Z.m?Z.m(d,b,c):Z.call(null,d,b,c);H(b," ")}if(a.Kb)return a.Xb(a,b,c);if(a!=null?a.j&2147483648||u===a.Y||(a.j?0:w(Ua,a)):w(Ua,a))return Va(a,b,c);if(a===!0||a===!1)return H(b,z.g(a));if(typeof a==="number")return H(b,isNaN(a)?"##NaN":a===Number.POSITIVE_INFINITY?"##Inf":a===Number.NEGATIVE_INFINITY?"##-Inf":z.g(a));if(a!=null&&a.constructor===Object)return H(b,"#js "),d=X.h(function(g){var h=/[A-Za-z_\*\+\?!\-'][\w\*\+\?!\-']*/;
if(typeof g==="string")if(h=h.exec(g),h!=null&&R.h(h[0],g))if(h.length===1)h=h[0];else if(v(Cd.g?Cd.g(h):Cd.call(null,h)))h=new Y(null,2,5,pd,[Od.g?Od.g(h):Od.call(null,h),Pd.g?Pd.g(h):Pd.call(null,h)],null);else if(lc(h))h=gc(h,null);else if(ha(h))b:{var k=h.length;if(k<32)h=new Y(null,k,5,pd,h,null);else{for(var l=32,m=(new Y(null,32,5,pd,h.slice(0,32),null)).Xa(null);;)if(l<k){var n=l+1;m=Xa(m,h[l]);l=n}else{h=Ya(m);break b}h=void 0}}else h=Ya(sc(Xa,Wa(Yb),h));else h=null;else throw new TypeError("re-matches must match against a string.");
return new Bd(h!=null?Ec.g(g):g,a[g])},da(a)),ze.ea?ze.ea(d,Z,b,c):ze.call(null,d,Z,b,c);if(ha(a))return se(b,Z,"#js ["," ","]",c,a);if(typeof a==="string")return v(ib.g(c))?H(b,we(a)):H(b,a);if(typeof a==="function"){var e=a.name;c=v(function(){var g=e==null;return g?g:/^[\s\xa0]*$/.test(e)}())?"Function":e;return ue(b,Wb(["#object[",c,v(!1)?[' "',z.g(a),'"'].join(""):"","]"]))}if(a instanceof Date)return c=function(g,h){for(g=z.g(g);;)if(g.length<h)g=["0",g].join("");else return g},ue(b,Wb(['#inst "',
c(a.getUTCFullYear(),4),"-",c(a.getUTCMonth()+1,2),"-",c(a.getUTCDate(),2),"T",c(a.getUTCHours(),2),":",c(a.getUTCMinutes(),2),":",c(a.getUTCSeconds(),2),".",c(a.getUTCMilliseconds(),3),"-",'00:00"']));if(a instanceof RegExp)return ue(b,Wb(['#"',a.source,'"']));if(t(a)==="symbol"||typeof Symbol!=="undefined"&&a instanceof Symbol)return ue(b,Wb(["#object[",a.toString(),"]"]));if(v(function(){var g=a==null?null:a.constructor;return g==null?null:g.pb}()))return ue(b,Wb(["#object[",a.constructor.pb.replace(RegExp("/",
"g"),"."),"]"]));e=function(){var g=a==null?null:a.constructor;return g==null?null:g.name}();c=v(function(){var g=e==null;return g?g:/^[\s\xa0]*$/.test(e)}())?"Object":e;return a.constructor==null?ue(b,Wb(["#object[",c,"]"])):ue(b,Wb(["#object[",c," ",z.g(a),"]"]))}function Z(a,b,c){var d=Ae.g(c);return v(d)?(c=bc.m(c,Be,ye),d.m?d.m(a,b,c):d.call(null,a,b,c)):ye(a,b,c)}function Ce(a){return a instanceof wb?Ab.h(null,Fc(a)):Ec.h(null,Fc(a))}
function De(a){if(v(!1)){var b=J(a),c=J(b),d=N(c);P(c);ac(d,0,null);ac(d,1,null);c=a==null?null:a!=null&&(a.j&4||u===a.Bb)?a.W(null):(a!=null?a.j&4||u===a.Bb||(a.j?0:w(ma,a)):w(ma,a))?na(a):null;for(a=null;;){d=a;b=J(b);a=N(b);var e=P(b),g=a;a=ac(g,0,null);b=ac(g,1,null);if(v(g))if(a instanceof I||a instanceof wb)if(v(d))if(R.h(d,Dc(a))){c=bc.m(c,Ce(a),b);a=d;b=e;continue}else return null;else if(d=Dc(a),v(d)){c=bc.m(c,Ce(a),b);a=d;b=e;continue}else return null;else return null;else return new Y(null,
2,5,pd,[d,c],null);break}}else return null}function Ee(a,b,c,d,e){return se(d,function(g,h,k){var l=Ba(g);c.m?c.m(l,h,k):c.call(null,l,h,k);H(h," ");g=Ca(g);return c.m?c.m(g,h,k):c.call(null,g,h,k)},[z.g(a),"{"].join(""),", ","}",e,J(b))}function ze(a,b,c,d){var e=jc(a)?De(a):null,g=ac(e,0,null);e=ac(e,1,null);return v(g)?Ee(["#:",z.g(g)].join(""),e,b,c,d):Ee(null,a,b,c,d)}M.prototype.Y=u;M.prototype.J=function(a,b,c){return se(b,Z,"("," ",")",c,this)};Gc.prototype.Y=u;
Gc.prototype.J=function(a,b,c){return se(b,Z,"("," ",")",c,this)};Bd.prototype.Y=u;Bd.prototype.J=function(a,b,c){return se(b,Z,"["," ","]",c,this)};ie.prototype.Y=u;ie.prototype.J=function(a,b,c){return se(b,Z,"("," ",")",c,this)};Dd.prototype.Y=u;Dd.prototype.J=function(a,b,c){return se(b,Z,"("," ",")",c,this)};Fb.prototype.Y=u;Fb.prototype.J=function(a,b,c){return se(b,Z,"("," ",")",c,this)};qd.prototype.Y=u;qd.prototype.J=function(a,b,c){return se(b,Z,"("," ",")",c,this)};Cc.prototype.Y=u;
Cc.prototype.J=function(a,b,c){return se(b,Z,"("," ",")",c,this)};ne.prototype.Y=u;ne.prototype.J=function(a,b,c){return ze(this,Z,b,c)};ke.prototype.Y=u;ke.prototype.J=function(a,b,c){return se(b,Z,"("," ",")",c,this)};Kc.prototype.Y=u;Kc.prototype.J=function(a,b,c){return se(b,Z,"("," ",")",c,this)};re.prototype.Y=u;re.prototype.J=function(a,b,c){return se(b,Z,"("," ",")",c,this)};Y.prototype.Y=u;Y.prototype.J=function(a,b,c){return se(b,Z,"["," ","]",c,this)};Bc.prototype.Y=u;
Bc.prototype.J=function(a,b){return H(b,"()")};gb.prototype.Y=u;gb.prototype.J=function(a,b,c){return ze(this,Z,b,c)};qe.prototype.Y=u;qe.prototype.J=function(a,b,c){return se(b,Z,"("," ",")",c,this)};Zb.prototype.Y=u;Zb.prototype.J=function(a,b,c){return se(b,Z,"("," ",")",c,this)};var jb=new I(null,"meta","meta",1499536964),lb=new I(null,"print-length","print-length",1931866356),hb=new I(null,"flush-on-newline","flush-on-newline",-151457939),kb=new I(null,"dup","dup",556298533),ib=new I(null,"readably","readably",1129599760),Be=new I(null,"fallback-impl","fallback-impl",-1501286995),te=new I(null,"more-marker","more-marker",-14717935),Ae=new I(null,"alt-impl","alt-impl",670969595);var Fe=shadow$bridge("@babylonjs/core/Cameras/freeCamera");var Ge=shadow$bridge("@babylonjs/core/Engines/engine");var He=shadow$bridge("@babylonjs/core/Lights");shadow$bridge("@babylonjs/core/Loading/loadingScreen");var Ie=shadow$bridge("@babylonjs/core/Loading/sceneLoader");shadow$bridge("@babylonjs/core/Materials/standardMaterial");var Je=shadow$bridge("@babylonjs/core/Maths/math.vector");shadow$bridge("@babylonjs/core/Physics/physicsEngineComponent.js");var Ke=shadow$bridge("@babylonjs/core/Physics/v2/IPhysicsEnginePlugin");var Le=shadow$bridge("@babylonjs/core/Physics/v2/physicsAggregate");var Me=shadow$bridge("@babylonjs/core/Physics/v2/Plugins/havokPlugin");var Ne=shadow$bridge("@babylonjs/core/scene");var Oe=shadow$bridge("@babylonjs/havok").default;function Pe(){var a=document.getElementById("render");a.innerHTML="";return a}shadow$bridge("@babylonjs/loaders/dynamic").registerBuiltInLoaders();
Oe({locateFile:function(){return"havok.wasm"}}).then(function(a){var b=new Me.HavokPlugin(!0,a),c=Pe(),d=new Ge.Engine(c,!0,{stencil:!0,preserveDrawingBuffer:!0,disableWebGL2Support:!1}),e=new Ne.Scene(d),g=new He.HemisphericLight("HemiLight",new Je.Vector3(0,1,0),e),h=new Fe.FreeCamera("camera1",new Je.Vector3(0,5,-10),e);return Ie.AppendSceneAsync("assets/test-scene.glb",e).then(function(){g.intensity=1;h.setTarget(Je.Vector3.Zero());h.attachControl(c,!0);e.enablePhysics(new Je.Vector3(0,-9.8,0),
b);for(var k=J(e.meshes),l=null,m=0,n=0;;)if(n<m){var p=l.X(null,n),q=p.metadata;if(v(q))if(q=q.gltf.extras,q=new Y(null,2,5,pd,[q.collider_type,q.collider_shape],null),R.h(new Y(null,2,5,pd,["static","box"],null),q))new Le.PhysicsAggregate(p,Ke.PhysicsShapeType.BOX,{mass:0},e);else if(R.h(new Y(null,2,5,pd,["dynamic","box"],null),q))new Le.PhysicsAggregate(p,Ke.PhysicsShapeType.BOX,{mass:1},e);else if(R.h(new Y(null,2,5,pd,["dynamic","sphere"],null),q))new Le.PhysicsAggregate(p,Ke.PhysicsShapeType.SPHERE,
{mass:1,restitution:.5},e);else throw Error(["No matching clause: ",z.g(q)].join(""));n+=1}else if(k=J(k)){if(mc(k))m=ab(k),k=bb(k),l=m,m=U(m);else{l=N(k);m=l.metadata;if(v(m))if(m=m.gltf.extras,m=new Y(null,2,5,pd,[m.collider_type,m.collider_shape],null),R.h(new Y(null,2,5,pd,["static","box"],null),m))new Le.PhysicsAggregate(l,Ke.PhysicsShapeType.BOX,{mass:0},e);else if(R.h(new Y(null,2,5,pd,["dynamic","box"],null),m))new Le.PhysicsAggregate(l,Ke.PhysicsShapeType.BOX,{mass:1},e);else if(R.h(new Y(null,
2,5,pd,["dynamic","sphere"],null),m))new Le.PhysicsAggregate(l,Ke.PhysicsShapeType.SPHERE,{mass:1,restitution:.5},e);else throw Error(["No matching clause: ",z.g(m)].join(""));k=P(k);l=null;m=0}n=0}else break;return d.runRenderLoop(function(){return v(e)?e.render():null})})});
}).call(this);